import { ValidationError } from '../../../../errors/index.js';
import type { BlueprintApprovalModule, BlueprintAutomationAction, BlueprintAutomationTrigger, BlueprintPermissionAction, ProcessBlueprint } from './process-blueprint.types.js';
const PERMISSIONS: readonly BlueprintPermissionAction[] = ['CREATE', 'READ', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT']; const APPROVALS: readonly BlueprintApprovalModule[] = ['PURCHASE_REQUEST', 'LEAVE_REQUEST', 'INVOICE', 'SALES_ORDER', 'PURCHASE_ORDER', 'SERVICE_REQUEST', 'OTHER']; const TRIGGERS: readonly BlueprintAutomationTrigger[] = ['LOW_STOCK', 'OVERDUE_INVOICE', 'HIGH_VALUE_INVOICE', 'LOW_MARGIN', 'CHECK_DUE_SOON']; const ACTIONS: readonly BlueprintAutomationAction[] = ['CREATE_TASK', 'CREATE_NOTIFICATION', 'DRAFT_REMINDER_EMAIL', 'REQUEST_APPROVAL', 'CREATE_PURCHASE_REQUEST_DRAFT'];
const isRecord = (value: unknown): value is Record<string, unknown> => typeof value === 'object' && value !== null && !Array.isArray(value); const required = (value: unknown, field: string): string => { if (typeof value !== 'string' || !value.trim()) throw new ValidationError(`${field} zorunludur.`); return value; }; const nullable = (value: unknown): string | null => typeof value === 'string' ? value : null;
function enumeration<T extends string>(value: unknown, values: readonly T[], field: string): T { if (typeof value !== 'string' || !values.includes(value as T)) throw new ValidationError(`${field} geçersiz.`); return value as T; }
export function parseProcessBlueprint(value: unknown): ProcessBlueprint {
  if (!isRecord(value) || !isRecord(value.content) || value.schemaVersion !== 1) throw new ValidationError('Süreç paketi contractı geçersiz.'); const content = value.content;
  const roles = Array.isArray(content.roles) ? content.roles.map((item) => { if (!isRecord(item)) throw new ValidationError('Rol tanımı geçersiz.'); return { name: required(item.name, 'role.name'), description: nullable(item.description), permissions: Array.isArray(item.permissions) ? item.permissions.map((permission) => { if (!isRecord(permission)) throw new ValidationError('Yetki tanımı geçersiz.'); return { module: required(permission.module, 'permission.module'), action: enumeration(permission.action, PERMISSIONS, 'permission.action') }; }) : [] }; }) : [];
  const numberSequences = Array.isArray(content.numberSequences) ? content.numberSequences.map((item) => { if (!isRecord(item)) throw new ValidationError('Numara serisi geçersiz.'); return { module: required(item.module, 'sequence.module'), prefix: typeof item.prefix === 'string' ? item.prefix : '', padding: typeof item.padding === 'number' && Number.isInteger(item.padding) && item.padding > 0 ? item.padding : 6 }; }) : [];
  const approvalFlows = Array.isArray(content.approvalFlows) ? content.approvalFlows.map((item) => { if (!isRecord(item)) throw new ValidationError('Onay akışı geçersiz.'); return { name: required(item.name, 'flow.name'), module: enumeration(item.module, APPROVALS, 'flow.module'), isActive: item.isActive !== false, conditions: item.conditions ?? null, steps: Array.isArray(item.steps) ? item.steps.map((step) => { if (!isRecord(step)) throw new ValidationError('Onay adımı geçersiz.'); return { stepOrder: typeof step.stepOrder === 'number' ? step.stepOrder : 1, name: required(step.name, 'step.name'), approverRoleName: nullable(step.approverRoleName), isRequired: step.isRequired !== false }; }) : [] }; }) : [];
  const automationRules = Array.isArray(content.automationRules) ? content.automationRules.map((item) => { if (!isRecord(item)) throw new ValidationError('Otomasyon tanımı geçersiz.'); return { name: required(item.name, 'automation.name'), description: nullable(item.description), trigger: enumeration(item.trigger, TRIGGERS, 'automation.trigger'), action: enumeration(item.action, ACTIONS, 'automation.action'), module: required(item.module, 'automation.module'), conditions: item.conditions ?? null, actionConfig: item.actionConfig ?? null, isActive: item.isActive !== false }; }) : [];
  const moduleSettings = Array.isArray(content.moduleSettings) ? content.moduleSettings.map((item) => { if (!isRecord(item)) throw new ValidationError('Modül ayarı geçersiz.'); return { module: required(item.module, 'setting.module'), key: required(item.key, 'setting.key'), value: typeof item.value === 'string' ? item.value : '' }; }) : [];
  return { schemaVersion: 1, key: required(value.key, 'key'), name: required(value.name, 'name'), description: nullable(value.description), industry: typeof value.industry === 'string' ? value.industry : 'CUSTOM', version: typeof value.version === 'number' && Number.isInteger(value.version) ? value.version : 1, createdAt: typeof value.createdAt === 'string' ? value.createdAt : new Date().toISOString(), content: { roles, numberSequences, approvalFlows, automationRules, moduleSettings } };
}
