import { NotFoundError, ValidationError } from '../../../../errors/index.js';
import type { ProcessBlueprintRepository } from './process-blueprint.port.js';
import type { BlueprintDifference, BlueprintPreview, BlueprintSection, BlueprintSummary, ProcessBlueprint, ProcessBlueprintContent } from './process-blueprint.types.js';
export const BLUEPRINT_SECTIONS: readonly BlueprintSection[] = ['roles', 'numberSequences', 'approvalFlows', 'automationRules', 'moduleSettings'];
const sectionKey = { roles: (value: ProcessBlueprintContent['roles'][number]) => value.name, numberSequences: (value: ProcessBlueprintContent['numberSequences'][number]) => value.module, approvalFlows: (value: ProcessBlueprintContent['approvalFlows'][number]) => `${value.module}:${value.name}`, automationRules: (value: ProcessBlueprintContent['automationRules'][number]) => value.name, moduleSettings: (value: ProcessBlueprintContent['moduleSettings'][number]) => `${value.module}:${value.key}` };
function summary(value: ProcessBlueprint): BlueprintSummary { return { key: value.key, name: value.name, description: value.description, industry: value.industry, version: value.version, createdAt: value.createdAt, counts: { roles: value.content.roles.length, numberSequences: value.content.numberSequences.length, approvalFlows: value.content.approvalFlows.length, automationRules: value.content.automationRules.length, moduleSettings: value.content.moduleSettings.length } }; }
function selected(input: readonly string[]): BlueprintSection[] { const result = input.filter((value): value is BlueprintSection => BLUEPRINT_SECTIONS.includes(value as BlueprintSection)); if (!result.length) throw new ValidationError('En az bir geçerli paket bölümü seçilmelidir.'); return [...new Set(result)]; }
export class ProcessBlueprintService {
  constructor(private readonly repository: ProcessBlueprintRepository) {}
  async list(tenantId: string): Promise<BlueprintSummary[]> { return (await this.repository.list(tenantId)).map(summary).sort((a, b) => b.createdAt.localeCompare(a.createdAt)); }
  async create(tenantId: string, input: { key: string; name: string; description?: string; industry?: string }): Promise<ProcessBlueprint> { const key = input.key.trim().toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, ''); if (!key || !input.name.trim()) throw new ValidationError('Paket anahtarı ve adı zorunludur.'); const previous = (await this.repository.list(tenantId)).filter((item) => item.key === key); const blueprint: ProcessBlueprint = { schemaVersion: 1, key, name: input.name.trim(), description: input.description?.trim() || null, industry: input.industry?.trim() || 'CUSTOM', version: Math.max(0, ...previous.map((item) => item.version)) + 1, createdAt: new Date().toISOString(), content: await this.repository.snapshot(tenantId) }; await this.repository.save(tenantId, blueprint); return blueprint; }
  async export(tenantId: string, key: string, version?: number): Promise<ProcessBlueprint> { return this.find(tenantId, key, version); }
  async preview(tenantId: string, blueprint: ProcessBlueprint, inputSections: readonly string[]): Promise<BlueprintPreview> { const sections = selected(inputSections); const current = await this.repository.snapshot(tenantId); const differences: BlueprintDifference[] = []; for (const section of sections) { const keyOf = sectionKey[section] as (value: never) => string; const existing = new Map((current[section] as never[]).map((item) => [keyOf(item), JSON.stringify(item)])); for (const item of blueprint.content[section] as never[]) { const key = keyOf(item); const old = existing.get(key); differences.push({ section, key, action: old === undefined ? 'CREATE' : old === JSON.stringify(item) ? 'UNCHANGED' : 'UPDATE' }); } } return { blueprint: summary(blueprint), selectedSections: sections, differences, changes: differences.filter((item) => item.action !== 'UNCHANGED').length }; }
  async apply(tenantId: string, blueprint: ProcessBlueprint, inputSections: readonly string[]): Promise<BlueprintPreview> { const preview = await this.preview(tenantId, blueprint, inputSections); await this.repository.apply(tenantId, blueprint, preview.selectedSections); return preview; }
  async import(tenantId: string, blueprint: ProcessBlueprint): Promise<ProcessBlueprint> { if (blueprint.schemaVersion !== 1 || !blueprint.key || !blueprint.name) throw new ValidationError('Desteklenmeyen süreç paketi.'); const versions = (await this.repository.list(tenantId)).filter((item) => item.key === blueprint.key).map((item) => item.version); const imported = { ...blueprint, version: Math.max(0, ...versions) + 1, createdAt: new Date().toISOString() }; await this.repository.save(tenantId, imported); return imported; }
  private async find(tenantId: string, key: string, version?: number) { const items = (await this.repository.list(tenantId)).filter((item) => item.key === key && (version === undefined || item.version === version)).sort((a, b) => b.version - a.version); if (!items[0]) throw new NotFoundError('Süreç paketi', key); return items[0]; }
}
