export const PLAN = {
  STARTER: 'STARTER',
  PROFESSIONAL: 'PROFESSIONAL',
  ENTERPRISE: 'ENTERPRISE',
};

export const PLAN_RANK = {
  [PLAN.STARTER]: 1,
  [PLAN.PROFESSIONAL]: 2,
  [PLAN.ENTERPRISE]: 3,
};

export const FEATURE_KEY = {
  MAX_USERS: 'MAX_USERS',
  MAX_PRODUCTS: 'MAX_PRODUCTS',
  MULTI_WAREHOUSE: 'MULTI_WAREHOUSE',
  ROLE_MANAGEMENT: 'ROLE_MANAGEMENT',
  APPROVALS: 'APPROVALS',
  CRM: 'CRM',
  SALES: 'SALES',
  PURCHASING: 'PURCHASING',
  PRODUCTION: 'PRODUCTION',
  SERVICE: 'SERVICE',
  MARKETPLACE: 'MARKETPLACE',
  PAYROLL: 'PAYROLL',
  HR: 'HR',
  API_ACCESS: 'API_ACCESS',
  AUDIT_LOG: 'AUDIT_LOG',
  CUSTOM_REPORTING: 'CUSTOM_REPORTING',
};

export const FEATURE_TYPE = {
  BOOLEAN: 'BOOLEAN',
  LIMIT: 'LIMIT',
  ENUM: 'ENUM',
};

export const MODULE_KEY = {
  ACCOUNTING: 'accounting',
  INVENTORY: 'inventory',
  CONTACTS: 'contacts',
  INVOICING: 'invoicing',
  REPORTING: 'reporting',
  PURCHASING: 'purchasing',
  PRODUCTION: 'production',
  SERVICE: 'service',
  MARKETPLACE: 'marketplace',
  PAYROLL: 'payroll',
  HR: 'hr',
  APPROVALS: 'approvals',
  WAREHOUSE: 'warehouse',
  MAIL: 'mail',
  WORKFLOW: 'workflow',
  DOCUMENTS: 'documents',
};

export const STARTER_OPEN_MODULES = [
  MODULE_KEY.ACCOUNTING,
  MODULE_KEY.INVENTORY,
  MODULE_KEY.CONTACTS,
  MODULE_KEY.INVOICING,
  MODULE_KEY.REPORTING,
  MODULE_KEY.DOCUMENTS,
];

export const PLAN_FEATURES = {
  [PLAN.STARTER]: {
    maxUsers: 5,
    maxProducts: 500,
    multiWarehouse: false,
    roleManagement: false,
    approvals: false,
    crm: true,
    sales: true,
    purchasing: false,
    production: false,
    service: false,
    marketplace: false,
    payroll: false,
    hr: false,
    apiAccess: false,
    advancedAuditLog: false,
    customReporting: false,
    documentCenter: true,
    smartNotifications: true,
    workflowCenter: false,
    mailCenter: false,
  },
  [PLAN.PROFESSIONAL]: {
    maxUsers: 25,
    maxProducts: 5000,
    multiWarehouse: true,
    roleManagement: true,
    approvals: true,
    crm: true,
    sales: true,
    purchasing: true,
    production: false,
    service: false,
    marketplace: false,
    payroll: false,
    hr: false,
    apiAccess: true,
    advancedAuditLog: true,
    customReporting: true,
    documentCenter: true,
    smartNotifications: true,
    workflowCenter: true,
    mailCenter: false,
  },
  [PLAN.ENTERPRISE]: {
    maxUsers: null,
    maxProducts: null,
    multiWarehouse: true,
    roleManagement: true,
    approvals: true,
    crm: true,
    sales: true,
    purchasing: true,
    production: true,
    service: true,
    marketplace: true,
    payroll: true,
    hr: true,
    apiAccess: true,
    advancedAuditLog: true,
    customReporting: true,
    documentCenter: true,
    smartNotifications: true,
    workflowCenter: true,
    mailCenter: true,
  },
};

export const PLAN_MODULES = {
  [PLAN.STARTER]: [
    MODULE_KEY.ACCOUNTING,
    MODULE_KEY.INVENTORY,
    MODULE_KEY.CONTACTS,
    MODULE_KEY.INVOICING,
    MODULE_KEY.REPORTING,
    MODULE_KEY.DOCUMENTS,
  ],
  [PLAN.PROFESSIONAL]: [
    MODULE_KEY.ACCOUNTING,
    MODULE_KEY.INVENTORY,
    MODULE_KEY.CONTACTS,
    MODULE_KEY.INVOICING,
    MODULE_KEY.REPORTING,
    MODULE_KEY.DOCUMENTS,
    MODULE_KEY.PURCHASING,
    MODULE_KEY.APPROVALS,
    MODULE_KEY.WAREHOUSE,
    MODULE_KEY.WORKFLOW,
  ],
  [PLAN.ENTERPRISE]: [
    MODULE_KEY.ACCOUNTING,
    MODULE_KEY.INVENTORY,
    MODULE_KEY.CONTACTS,
    MODULE_KEY.INVOICING,
    MODULE_KEY.REPORTING,
    MODULE_KEY.DOCUMENTS,
    MODULE_KEY.PURCHASING,
    MODULE_KEY.APPROVALS,
    MODULE_KEY.WAREHOUSE,
    MODULE_KEY.WORKFLOW,
    MODULE_KEY.PRODUCTION,
    MODULE_KEY.SERVICE,
    MODULE_KEY.MARKETPLACE,
    MODULE_KEY.HR,
    MODULE_KEY.PAYROLL,
    MODULE_KEY.MAIL,
  ],
};

export const PLAN_FEATURE_ROWS = [
  { plan: PLAN.STARTER, key: 'max_users', featureKey: FEATURE_KEY.MAX_USERS, value: '5', type: FEATURE_TYPE.LIMIT },
  { plan: PLAN.STARTER, key: 'max_products', featureKey: FEATURE_KEY.MAX_PRODUCTS, value: '500', type: FEATURE_TYPE.LIMIT },
  { plan: PLAN.STARTER, key: 'multi_warehouse', featureKey: FEATURE_KEY.MULTI_WAREHOUSE, value: 'false', type: FEATURE_TYPE.BOOLEAN },
  { plan: PLAN.STARTER, key: 'role_management', featureKey: FEATURE_KEY.ROLE_MANAGEMENT, value: 'false', type: FEATURE_TYPE.BOOLEAN },
  { plan: PLAN.STARTER, key: 'approvals', featureKey: FEATURE_KEY.APPROVALS, value: 'false', type: FEATURE_TYPE.BOOLEAN },
  { plan: PLAN.STARTER, key: 'crm', featureKey: FEATURE_KEY.CRM, value: 'true', type: FEATURE_TYPE.BOOLEAN },
  { plan: PLAN.STARTER, key: 'sales', featureKey: FEATURE_KEY.SALES, value: 'true', type: FEATURE_TYPE.BOOLEAN },
  { plan: PLAN.STARTER, key: 'purchasing', featureKey: FEATURE_KEY.PURCHASING, value: 'false', type: FEATURE_TYPE.BOOLEAN },
  { plan: PLAN.STARTER, key: 'production', featureKey: FEATURE_KEY.PRODUCTION, value: 'false', type: FEATURE_TYPE.BOOLEAN },
  { plan: PLAN.STARTER, key: 'service', featureKey: FEATURE_KEY.SERVICE, value: 'false', type: FEATURE_TYPE.BOOLEAN },
  { plan: PLAN.STARTER, key: 'marketplace', featureKey: FEATURE_KEY.MARKETPLACE, value: 'false', type: FEATURE_TYPE.BOOLEAN },
  { plan: PLAN.STARTER, key: 'payroll', featureKey: FEATURE_KEY.PAYROLL, value: 'false', type: FEATURE_TYPE.BOOLEAN },
  { plan: PLAN.STARTER, key: 'hr', featureKey: FEATURE_KEY.HR, value: 'false', type: FEATURE_TYPE.BOOLEAN },
  { plan: PLAN.STARTER, key: 'api_access', featureKey: FEATURE_KEY.API_ACCESS, value: 'false', type: FEATURE_TYPE.BOOLEAN },
  { plan: PLAN.STARTER, key: 'audit_log', featureKey: FEATURE_KEY.AUDIT_LOG, value: 'basic', type: FEATURE_TYPE.ENUM },
  { plan: PLAN.STARTER, key: 'custom_reporting', featureKey: FEATURE_KEY.CUSTOM_REPORTING, value: 'false', type: FEATURE_TYPE.BOOLEAN },
  { plan: PLAN.PROFESSIONAL, key: 'max_users', featureKey: FEATURE_KEY.MAX_USERS, value: '25', type: FEATURE_TYPE.LIMIT },
  { plan: PLAN.PROFESSIONAL, key: 'max_products', featureKey: FEATURE_KEY.MAX_PRODUCTS, value: '5000', type: FEATURE_TYPE.LIMIT },
  { plan: PLAN.PROFESSIONAL, key: 'multi_warehouse', featureKey: FEATURE_KEY.MULTI_WAREHOUSE, value: 'true', type: FEATURE_TYPE.BOOLEAN },
  { plan: PLAN.PROFESSIONAL, key: 'role_management', featureKey: FEATURE_KEY.ROLE_MANAGEMENT, value: 'true', type: FEATURE_TYPE.BOOLEAN },
  { plan: PLAN.PROFESSIONAL, key: 'approvals', featureKey: FEATURE_KEY.APPROVALS, value: 'true', type: FEATURE_TYPE.BOOLEAN },
  { plan: PLAN.PROFESSIONAL, key: 'crm', featureKey: FEATURE_KEY.CRM, value: 'true', type: FEATURE_TYPE.BOOLEAN },
  { plan: PLAN.PROFESSIONAL, key: 'sales', featureKey: FEATURE_KEY.SALES, value: 'true', type: FEATURE_TYPE.BOOLEAN },
  { plan: PLAN.PROFESSIONAL, key: 'purchasing', featureKey: FEATURE_KEY.PURCHASING, value: 'true', type: FEATURE_TYPE.BOOLEAN },
  { plan: PLAN.PROFESSIONAL, key: 'production', featureKey: FEATURE_KEY.PRODUCTION, value: 'false', type: FEATURE_TYPE.BOOLEAN },
  { plan: PLAN.PROFESSIONAL, key: 'service', featureKey: FEATURE_KEY.SERVICE, value: 'false', type: FEATURE_TYPE.BOOLEAN },
  { plan: PLAN.PROFESSIONAL, key: 'marketplace', featureKey: FEATURE_KEY.MARKETPLACE, value: 'false', type: FEATURE_TYPE.BOOLEAN },
  { plan: PLAN.PROFESSIONAL, key: 'payroll', featureKey: FEATURE_KEY.PAYROLL, value: 'false', type: FEATURE_TYPE.BOOLEAN },
  { plan: PLAN.PROFESSIONAL, key: 'hr', featureKey: FEATURE_KEY.HR, value: 'false', type: FEATURE_TYPE.BOOLEAN },
  { plan: PLAN.PROFESSIONAL, key: 'api_access', featureKey: FEATURE_KEY.API_ACCESS, value: 'true', type: FEATURE_TYPE.BOOLEAN },
  { plan: PLAN.PROFESSIONAL, key: 'audit_log', featureKey: FEATURE_KEY.AUDIT_LOG, value: 'standard', type: FEATURE_TYPE.ENUM },
  { plan: PLAN.PROFESSIONAL, key: 'custom_reporting', featureKey: FEATURE_KEY.CUSTOM_REPORTING, value: 'true', type: FEATURE_TYPE.BOOLEAN },
  { plan: PLAN.ENTERPRISE, key: 'max_users', featureKey: FEATURE_KEY.MAX_USERS, value: 'unlimited', type: FEATURE_TYPE.LIMIT },
  { plan: PLAN.ENTERPRISE, key: 'max_products', featureKey: FEATURE_KEY.MAX_PRODUCTS, value: 'unlimited', type: FEATURE_TYPE.LIMIT },
  { plan: PLAN.ENTERPRISE, key: 'multi_warehouse', featureKey: FEATURE_KEY.MULTI_WAREHOUSE, value: 'true', type: FEATURE_TYPE.BOOLEAN },
  { plan: PLAN.ENTERPRISE, key: 'role_management', featureKey: FEATURE_KEY.ROLE_MANAGEMENT, value: 'true', type: FEATURE_TYPE.BOOLEAN },
  { plan: PLAN.ENTERPRISE, key: 'approvals', featureKey: FEATURE_KEY.APPROVALS, value: 'true', type: FEATURE_TYPE.BOOLEAN },
  { plan: PLAN.ENTERPRISE, key: 'crm', featureKey: FEATURE_KEY.CRM, value: 'true', type: FEATURE_TYPE.BOOLEAN },
  { plan: PLAN.ENTERPRISE, key: 'sales', featureKey: FEATURE_KEY.SALES, value: 'true', type: FEATURE_TYPE.BOOLEAN },
  { plan: PLAN.ENTERPRISE, key: 'purchasing', featureKey: FEATURE_KEY.PURCHASING, value: 'true', type: FEATURE_TYPE.BOOLEAN },
  { plan: PLAN.ENTERPRISE, key: 'production', featureKey: FEATURE_KEY.PRODUCTION, value: 'true', type: FEATURE_TYPE.BOOLEAN },
  { plan: PLAN.ENTERPRISE, key: 'service', featureKey: FEATURE_KEY.SERVICE, value: 'true', type: FEATURE_TYPE.BOOLEAN },
  { plan: PLAN.ENTERPRISE, key: 'marketplace', featureKey: FEATURE_KEY.MARKETPLACE, value: 'true', type: FEATURE_TYPE.BOOLEAN },
  { plan: PLAN.ENTERPRISE, key: 'payroll', featureKey: FEATURE_KEY.PAYROLL, value: 'true', type: FEATURE_TYPE.BOOLEAN },
  { plan: PLAN.ENTERPRISE, key: 'hr', featureKey: FEATURE_KEY.HR, value: 'true', type: FEATURE_TYPE.BOOLEAN },
  { plan: PLAN.ENTERPRISE, key: 'api_access', featureKey: FEATURE_KEY.API_ACCESS, value: 'true', type: FEATURE_TYPE.BOOLEAN },
  { plan: PLAN.ENTERPRISE, key: 'audit_log', featureKey: FEATURE_KEY.AUDIT_LOG, value: 'full', type: FEATURE_TYPE.ENUM },
  { plan: PLAN.ENTERPRISE, key: 'custom_reporting', featureKey: FEATURE_KEY.CUSTOM_REPORTING, value: 'true', type: FEATURE_TYPE.BOOLEAN },
];

export const ACCESS_POLICIES = {
  purchasing: { minPlan: PLAN.PROFESSIONAL, featureKey: FEATURE_KEY.PURCHASING, module: MODULE_KEY.PURCHASING },
  approvals: { minPlan: PLAN.PROFESSIONAL, featureKey: FEATURE_KEY.APPROVALS, module: MODULE_KEY.APPROVALS },
  apiKeys: { minPlan: PLAN.PROFESSIONAL, featureKey: FEATURE_KEY.API_ACCESS },
  roles: { minPlan: PLAN.PROFESSIONAL, featureKey: FEATURE_KEY.ROLE_MANAGEMENT },
  deliveryNotes: { minPlan: PLAN.PROFESSIONAL, module: MODULE_KEY.INVOICING },
  eDocuments: { minPlan: PLAN.PROFESSIONAL, module: MODULE_KEY.INVOICING },
  bankTransactions: { minPlan: PLAN.PROFESSIONAL, module: MODULE_KEY.ACCOUNTING },
  checkPromissory: { minPlan: PLAN.PROFESSIONAL, module: MODULE_KEY.ACCOUNTING },
  reconciliations: { minPlan: PLAN.PROFESSIONAL, module: MODULE_KEY.ACCOUNTING },
  stockValuations: { minPlan: PLAN.PROFESSIONAL, module: MODULE_KEY.INVENTORY },
  reservations: { minPlan: PLAN.PROFESSIONAL, module: MODULE_KEY.INVENTORY },
  productBatches: { minPlan: PLAN.PROFESSIONAL, module: MODULE_KEY.INVENTORY },
  lotSerials: { minPlan: PLAN.PROFESSIONAL, module: MODULE_KEY.INVENTORY },
  production: { minPlan: PLAN.ENTERPRISE, featureKey: FEATURE_KEY.PRODUCTION, module: MODULE_KEY.PRODUCTION },
  service: { minPlan: PLAN.ENTERPRISE, featureKey: FEATURE_KEY.SERVICE, module: MODULE_KEY.SERVICE },
  marketplace: { minPlan: PLAN.ENTERPRISE, featureKey: FEATURE_KEY.MARKETPLACE, module: MODULE_KEY.MARKETPLACE },
  hr: { minPlan: PLAN.ENTERPRISE, featureKey: FEATURE_KEY.HR, module: MODULE_KEY.HR },
  payroll: { minPlan: PLAN.ENTERPRISE, featureKey: FEATURE_KEY.PAYROLL, module: MODULE_KEY.PAYROLL },
  mail: { minPlan: PLAN.ENTERPRISE, featureKey: FEATURE_KEY.HR, module: MODULE_KEY.MAIL },
  chat: { minPlan: PLAN.ENTERPRISE },
  aiGovernance: { minPlan: PLAN.ENTERPRISE },
};

export function isPlanAtLeast(currentPlan, requiredPlan) {
  return PLAN_RANK[currentPlan] >= PLAN_RANK[requiredPlan];
}

export function normalizeModuleKey(module) {
  return String(module).toLowerCase();
}
