"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ACCESS_POLICIES = exports.PLAN_FEATURE_ROWS = exports.PLAN_MODULES = exports.PLAN_FEATURES = exports.STARTER_OPEN_MODULES = exports.MODULE_KEY = exports.FEATURE_TYPE = exports.FEATURE_KEY = exports.PLAN_RANK = exports.PLAN = void 0;
exports.isPlanAtLeast = isPlanAtLeast;
exports.normalizeModuleKey = normalizeModuleKey;
exports.PLAN = {
    STARTER: 'STARTER',
    PROFESSIONAL: 'PROFESSIONAL',
    ENTERPRISE: 'ENTERPRISE',
};
exports.PLAN_RANK = {
    [exports.PLAN.STARTER]: 1,
    [exports.PLAN.PROFESSIONAL]: 2,
    [exports.PLAN.ENTERPRISE]: 3,
};
exports.FEATURE_KEY = {
    MAX_USERS: 'MAX_USERS',
    MAX_PRODUCTS: 'MAX_PRODUCTS',
    MULTI_WAREHOUSE: 'MULTI_WAREHOUSE',
    ROLE_MANAGEMENT: 'ROLE_MANAGEMENT',
    APPROVALS: 'APPROVALS',
    CRM: 'CRM',
    SALES: 'SALES',
    PURCHASING: 'PURCHASING',
    PRODUCTION: 'PRODUCTION',
    SERVICE: 'SERVICE',
    MARKETPLACE: 'MARKETPLACE',
    PAYROLL: 'PAYROLL',
    HR: 'HR',
    API_ACCESS: 'API_ACCESS',
    AUDIT_LOG: 'AUDIT_LOG',
    CUSTOM_REPORTING: 'CUSTOM_REPORTING',
    DOCUMENT_CENTER: 'DOCUMENT_CENTER',
};
exports.FEATURE_TYPE = {
    BOOLEAN: 'BOOLEAN',
    LIMIT: 'LIMIT',
    ENUM: 'ENUM',
};
exports.MODULE_KEY = {
    ACCOUNTING: 'accounting',
    INVENTORY: 'inventory',
    CONTACTS: 'contacts',
    INVOICING: 'invoicing',
    REPORTING: 'reporting',
    PURCHASING: 'purchasing',
    PRODUCTION: 'production',
    SERVICE: 'service',
    MARKETPLACE: 'marketplace',
    PAYROLL: 'payroll',
    HR: 'hr',
    APPROVALS: 'approvals',
    WAREHOUSE: 'warehouse',
    MAIL: 'mail',
    WORKFLOW: 'workflow',
    DOCUMENTS: 'documents',
};
exports.STARTER_OPEN_MODULES = [
    exports.MODULE_KEY.ACCOUNTING,
    exports.MODULE_KEY.INVENTORY,
    exports.MODULE_KEY.CONTACTS,
    exports.MODULE_KEY.INVOICING,
    exports.MODULE_KEY.REPORTING,
    exports.MODULE_KEY.DOCUMENTS,
];
exports.PLAN_FEATURES = {
    [exports.PLAN.STARTER]: {
        maxUsers: 5,
        maxProducts: 500,
        multiWarehouse: false,
        roleManagement: false,
        approvals: false,
        crm: true,
        sales: true,
        purchasing: false,
        production: false,
        service: false,
        marketplace: false,
        payroll: false,
        hr: false,
        apiAccess: false,
        advancedAuditLog: false,
        customReporting: false,
        documentCenter: true,
        smartNotifications: true,
        workflowCenter: false,
        mailCenter: false,
    },
    [exports.PLAN.PROFESSIONAL]: {
        maxUsers: 25,
        maxProducts: 5000,
        multiWarehouse: true,
        roleManagement: true,
        approvals: true,
        crm: true,
        sales: true,
        purchasing: true,
        production: false,
        service: false,
        marketplace: false,
        payroll: false,
        hr: false,
        apiAccess: true,
        advancedAuditLog: true,
        customReporting: true,
        documentCenter: true,
        smartNotifications: true,
        workflowCenter: true,
        mailCenter: false,
    },
    [exports.PLAN.ENTERPRISE]: {
        maxUsers: null,
        maxProducts: null,
        multiWarehouse: true,
        roleManagement: true,
        approvals: true,
        crm: true,
        sales: true,
        purchasing: true,
        production: true,
        service: true,
        marketplace: true,
        payroll: true,
        hr: true,
        apiAccess: true,
        advancedAuditLog: true,
        customReporting: true,
        documentCenter: true,
        smartNotifications: true,
        workflowCenter: true,
        mailCenter: true,
    },
};
exports.PLAN_MODULES = {
    [exports.PLAN.STARTER]: [
        exports.MODULE_KEY.ACCOUNTING,
        exports.MODULE_KEY.INVENTORY,
        exports.MODULE_KEY.CONTACTS,
        exports.MODULE_KEY.INVOICING,
        exports.MODULE_KEY.REPORTING,
        exports.MODULE_KEY.DOCUMENTS,
    ],
    [exports.PLAN.PROFESSIONAL]: [
        exports.MODULE_KEY.ACCOUNTING,
        exports.MODULE_KEY.INVENTORY,
        exports.MODULE_KEY.CONTACTS,
        exports.MODULE_KEY.INVOICING,
        exports.MODULE_KEY.REPORTING,
        exports.MODULE_KEY.DOCUMENTS,
        exports.MODULE_KEY.PURCHASING,
        exports.MODULE_KEY.APPROVALS,
        exports.MODULE_KEY.WAREHOUSE,
        exports.MODULE_KEY.WORKFLOW,
    ],
    [exports.PLAN.ENTERPRISE]: [
        exports.MODULE_KEY.ACCOUNTING,
        exports.MODULE_KEY.INVENTORY,
        exports.MODULE_KEY.CONTACTS,
        exports.MODULE_KEY.INVOICING,
        exports.MODULE_KEY.REPORTING,
        exports.MODULE_KEY.DOCUMENTS,
        exports.MODULE_KEY.PURCHASING,
        exports.MODULE_KEY.APPROVALS,
        exports.MODULE_KEY.WAREHOUSE,
        exports.MODULE_KEY.WORKFLOW,
        exports.MODULE_KEY.PRODUCTION,
        exports.MODULE_KEY.SERVICE,
        exports.MODULE_KEY.MARKETPLACE,
        exports.MODULE_KEY.HR,
        exports.MODULE_KEY.PAYROLL,
        exports.MODULE_KEY.MAIL,
    ],
};
exports.PLAN_FEATURE_ROWS = [
    { plan: exports.PLAN.STARTER, key: 'max_users', featureKey: exports.FEATURE_KEY.MAX_USERS, value: '5', type: exports.FEATURE_TYPE.LIMIT },
    { plan: exports.PLAN.STARTER, key: 'max_products', featureKey: exports.FEATURE_KEY.MAX_PRODUCTS, value: '500', type: exports.FEATURE_TYPE.LIMIT },
    { plan: exports.PLAN.STARTER, key: 'multi_warehouse', featureKey: exports.FEATURE_KEY.MULTI_WAREHOUSE, value: 'false', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.STARTER, key: 'role_management', featureKey: exports.FEATURE_KEY.ROLE_MANAGEMENT, value: 'false', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.STARTER, key: 'approvals', featureKey: exports.FEATURE_KEY.APPROVALS, value: 'false', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.STARTER, key: 'crm', featureKey: exports.FEATURE_KEY.CRM, value: 'true', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.STARTER, key: 'sales', featureKey: exports.FEATURE_KEY.SALES, value: 'true', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.STARTER, key: 'purchasing', featureKey: exports.FEATURE_KEY.PURCHASING, value: 'false', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.STARTER, key: 'production', featureKey: exports.FEATURE_KEY.PRODUCTION, value: 'false', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.STARTER, key: 'service', featureKey: exports.FEATURE_KEY.SERVICE, value: 'false', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.STARTER, key: 'marketplace', featureKey: exports.FEATURE_KEY.MARKETPLACE, value: 'false', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.STARTER, key: 'payroll', featureKey: exports.FEATURE_KEY.PAYROLL, value: 'false', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.STARTER, key: 'hr', featureKey: exports.FEATURE_KEY.HR, value: 'false', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.STARTER, key: 'api_access', featureKey: exports.FEATURE_KEY.API_ACCESS, value: 'false', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.STARTER, key: 'audit_log', featureKey: exports.FEATURE_KEY.AUDIT_LOG, value: 'basic', type: exports.FEATURE_TYPE.ENUM },
    { plan: exports.PLAN.STARTER, key: 'custom_reporting', featureKey: exports.FEATURE_KEY.CUSTOM_REPORTING, value: 'false', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.STARTER, key: 'document_center', featureKey: exports.FEATURE_KEY.DOCUMENT_CENTER, value: 'true', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.PROFESSIONAL, key: 'max_users', featureKey: exports.FEATURE_KEY.MAX_USERS, value: '25', type: exports.FEATURE_TYPE.LIMIT },
    { plan: exports.PLAN.PROFESSIONAL, key: 'max_products', featureKey: exports.FEATURE_KEY.MAX_PRODUCTS, value: '5000', type: exports.FEATURE_TYPE.LIMIT },
    { plan: exports.PLAN.PROFESSIONAL, key: 'multi_warehouse', featureKey: exports.FEATURE_KEY.MULTI_WAREHOUSE, value: 'true', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.PROFESSIONAL, key: 'role_management', featureKey: exports.FEATURE_KEY.ROLE_MANAGEMENT, value: 'true', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.PROFESSIONAL, key: 'approvals', featureKey: exports.FEATURE_KEY.APPROVALS, value: 'true', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.PROFESSIONAL, key: 'crm', featureKey: exports.FEATURE_KEY.CRM, value: 'true', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.PROFESSIONAL, key: 'sales', featureKey: exports.FEATURE_KEY.SALES, value: 'true', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.PROFESSIONAL, key: 'purchasing', featureKey: exports.FEATURE_KEY.PURCHASING, value: 'true', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.PROFESSIONAL, key: 'production', featureKey: exports.FEATURE_KEY.PRODUCTION, value: 'false', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.PROFESSIONAL, key: 'service', featureKey: exports.FEATURE_KEY.SERVICE, value: 'false', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.PROFESSIONAL, key: 'marketplace', featureKey: exports.FEATURE_KEY.MARKETPLACE, value: 'false', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.PROFESSIONAL, key: 'payroll', featureKey: exports.FEATURE_KEY.PAYROLL, value: 'false', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.PROFESSIONAL, key: 'hr', featureKey: exports.FEATURE_KEY.HR, value: 'false', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.PROFESSIONAL, key: 'api_access', featureKey: exports.FEATURE_KEY.API_ACCESS, value: 'true', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.PROFESSIONAL, key: 'audit_log', featureKey: exports.FEATURE_KEY.AUDIT_LOG, value: 'standard', type: exports.FEATURE_TYPE.ENUM },
    { plan: exports.PLAN.PROFESSIONAL, key: 'custom_reporting', featureKey: exports.FEATURE_KEY.CUSTOM_REPORTING, value: 'true', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.PROFESSIONAL, key: 'document_center', featureKey: exports.FEATURE_KEY.DOCUMENT_CENTER, value: 'true', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.ENTERPRISE, key: 'max_users', featureKey: exports.FEATURE_KEY.MAX_USERS, value: 'unlimited', type: exports.FEATURE_TYPE.LIMIT },
    { plan: exports.PLAN.ENTERPRISE, key: 'max_products', featureKey: exports.FEATURE_KEY.MAX_PRODUCTS, value: 'unlimited', type: exports.FEATURE_TYPE.LIMIT },
    { plan: exports.PLAN.ENTERPRISE, key: 'multi_warehouse', featureKey: exports.FEATURE_KEY.MULTI_WAREHOUSE, value: 'true', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.ENTERPRISE, key: 'role_management', featureKey: exports.FEATURE_KEY.ROLE_MANAGEMENT, value: 'true', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.ENTERPRISE, key: 'approvals', featureKey: exports.FEATURE_KEY.APPROVALS, value: 'true', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.ENTERPRISE, key: 'crm', featureKey: exports.FEATURE_KEY.CRM, value: 'true', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.ENTERPRISE, key: 'sales', featureKey: exports.FEATURE_KEY.SALES, value: 'true', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.ENTERPRISE, key: 'purchasing', featureKey: exports.FEATURE_KEY.PURCHASING, value: 'true', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.ENTERPRISE, key: 'production', featureKey: exports.FEATURE_KEY.PRODUCTION, value: 'true', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.ENTERPRISE, key: 'service', featureKey: exports.FEATURE_KEY.SERVICE, value: 'true', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.ENTERPRISE, key: 'marketplace', featureKey: exports.FEATURE_KEY.MARKETPLACE, value: 'true', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.ENTERPRISE, key: 'payroll', featureKey: exports.FEATURE_KEY.PAYROLL, value: 'true', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.ENTERPRISE, key: 'hr', featureKey: exports.FEATURE_KEY.HR, value: 'true', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.ENTERPRISE, key: 'api_access', featureKey: exports.FEATURE_KEY.API_ACCESS, value: 'true', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.ENTERPRISE, key: 'audit_log', featureKey: exports.FEATURE_KEY.AUDIT_LOG, value: 'full', type: exports.FEATURE_TYPE.ENUM },
    { plan: exports.PLAN.ENTERPRISE, key: 'custom_reporting', featureKey: exports.FEATURE_KEY.CUSTOM_REPORTING, value: 'true', type: exports.FEATURE_TYPE.BOOLEAN },
    { plan: exports.PLAN.ENTERPRISE, key: 'document_center', featureKey: exports.FEATURE_KEY.DOCUMENT_CENTER, value: 'true', type: exports.FEATURE_TYPE.BOOLEAN },
];
exports.ACCESS_POLICIES = {
    purchasing: { minPlan: exports.PLAN.PROFESSIONAL, featureKey: exports.FEATURE_KEY.PURCHASING, module: exports.MODULE_KEY.PURCHASING },
    approvals: { minPlan: exports.PLAN.PROFESSIONAL, featureKey: exports.FEATURE_KEY.APPROVALS, module: exports.MODULE_KEY.APPROVALS },
    apiKeys: { minPlan: exports.PLAN.PROFESSIONAL, featureKey: exports.FEATURE_KEY.API_ACCESS },
    roles: { minPlan: exports.PLAN.PROFESSIONAL, featureKey: exports.FEATURE_KEY.ROLE_MANAGEMENT },
    deliveryNotes: { minPlan: exports.PLAN.PROFESSIONAL, module: exports.MODULE_KEY.INVOICING },
    documentCenter: { minPlan: exports.PLAN.STARTER, featureKey: exports.FEATURE_KEY.DOCUMENT_CENTER, module: exports.MODULE_KEY.DOCUMENTS },
    eDocuments: { minPlan: exports.PLAN.STARTER, module: exports.MODULE_KEY.INVOICING },
    bankTransactions: { minPlan: exports.PLAN.PROFESSIONAL, module: exports.MODULE_KEY.ACCOUNTING },
    checkPromissory: { minPlan: exports.PLAN.PROFESSIONAL, module: exports.MODULE_KEY.ACCOUNTING },
    reconciliations: { minPlan: exports.PLAN.PROFESSIONAL, module: exports.MODULE_KEY.ACCOUNTING },
    stockValuations: { minPlan: exports.PLAN.PROFESSIONAL, module: exports.MODULE_KEY.INVENTORY },
    reservations: { minPlan: exports.PLAN.PROFESSIONAL, module: exports.MODULE_KEY.INVENTORY },
    productBatches: { minPlan: exports.PLAN.PROFESSIONAL, module: exports.MODULE_KEY.INVENTORY },
    lotSerials: { minPlan: exports.PLAN.PROFESSIONAL, module: exports.MODULE_KEY.INVENTORY },
    production: { minPlan: exports.PLAN.ENTERPRISE, featureKey: exports.FEATURE_KEY.PRODUCTION, module: exports.MODULE_KEY.PRODUCTION },
    service: { minPlan: exports.PLAN.ENTERPRISE, featureKey: exports.FEATURE_KEY.SERVICE, module: exports.MODULE_KEY.SERVICE },
    marketplace: { minPlan: exports.PLAN.ENTERPRISE, featureKey: exports.FEATURE_KEY.MARKETPLACE, module: exports.MODULE_KEY.MARKETPLACE },
    hr: { minPlan: exports.PLAN.ENTERPRISE, featureKey: exports.FEATURE_KEY.HR, module: exports.MODULE_KEY.HR },
    payroll: { minPlan: exports.PLAN.ENTERPRISE, featureKey: exports.FEATURE_KEY.PAYROLL, module: exports.MODULE_KEY.PAYROLL },
    mail: { minPlan: exports.PLAN.ENTERPRISE, module: exports.MODULE_KEY.MAIL },
    chat: { minPlan: exports.PLAN.ENTERPRISE },
    aiGovernance: { minPlan: exports.PLAN.ENTERPRISE },
};
function isPlanAtLeast(currentPlan, requiredPlan) {
    return exports.PLAN_RANK[currentPlan] >= exports.PLAN_RANK[requiredPlan];
}
function normalizeModuleKey(module) {
    return String(module).toLowerCase();
}
