ALTER TYPE "FeatureKey" ADD VALUE IF NOT EXISTS 'CHAT_ENABLED';
ALTER TYPE "FeatureKey" ADD VALUE IF NOT EXISTS 'STORAGE_LIMIT_BYTES';
ALTER TYPE "FeatureKey" ADD VALUE IF NOT EXISTS 'CHAT_FILE_MAX_BYTES';
ALTER TYPE "FeatureKey" ADD VALUE IF NOT EXISTS 'CHAT_ATTACHMENTS_PER_MESSAGE';
ALTER TYPE "FeatureKey" ADD VALUE IF NOT EXISTS 'CHAT_MAX_GROUP_MEMBERS';
ALTER TYPE "FeatureKey" ADD VALUE IF NOT EXISTS 'CHAT_RETENTION_DAYS';
ALTER TYPE "FeatureKey" ADD VALUE IF NOT EXISTS 'CHAT_AUDIT_LEVEL';
