import { AuditAction, EntityType } from '@prisma/client';
import type { AuditFieldKind } from './types.js';

// ─────────────────────────────────────────────
// Audit Field Registry
// Tüm modül, entity, aksiyon, alan etiketleri
// ve alan tipleri bu dosyada tanımlanır.
// ─────────────────────────────────────────────

export const MODULE_LABELS: Record<string, string> = {
  accounting: 'Muhasebe',
  api_keys: 'API Anahtarı',
  approvals: 'Onay',
  attachments: 'Dosya',
  automation_rules: 'Otomasyon Kuralı',
  bank_accounts: 'Banka Hesabı',
  bank_transactions: 'Banka Hareketi',
  cash_accounts: 'Kasa',
  categories: 'Kategori',
  contacts: 'Cari',
  data_exchange: 'İçe / Dışa Aktarım',
  delivery_notes: 'İrsaliye',
  documents: 'Doküman',
  e_documents: 'E-Belge',
  hr: 'İnsan Kaynakları',
  inventory: 'Stok',
  invoicing: 'Fatura',
  mail: 'Mail',
  marketplace: 'Pazaryeri',
  payments: 'Ödeme',
  production: 'Üretim',
  products: 'Ürün',
  purchasing: 'Satın Alma',
  reporting: 'Rapor',
  roles: 'Rol Yönetimi',
  sales: 'Satış',
  service: 'Servis',
  settings: 'Ayar',
  stock: 'Stok',
  stock_movements: 'Stok Hareketi',
  tasks: 'Görev',
  users: 'Kullanıcı',
  workflow: 'İş Akışı',
};

export const ENTITY_LABELS: Record<EntityType, string> = {
  INVOICE: 'Fatura',
  PRODUCT: 'Ürün',
  CATEGORY: 'Kategori',
  CONTACT: 'Cari',
  EMPLOYEE: 'Personel',
  CUSTOMER_ASSET: 'Müşteri Varlığı',
  SERVICE_REQUEST: 'Servis Talebi',
  PURCHASE_ORDER: 'Satın Alma Siparişi',
  SALES_QUOTE: 'Teklif',
  SALES_ORDER: 'Satış Siparişi',
  WORK_ORDER: 'İş Emri',
  DELIVERY_NOTE: 'İrsaliye',
  OTHER: 'Kayıt',
};

export const ACTION_LABELS: Record<AuditAction, string> = {
  CREATE: 'Oluşturma',
  UPDATE: 'Güncelleme',
  DELETE: 'Silme',
  APPROVE: 'Onay',
  REJECT: 'Red',
  EXPORT: 'Dışa Aktarma',
  LOGIN: 'Giriş',
  LOGOUT: 'Çıkış',
  OTHER: 'Diğer',
};

export const ACTION_VERBS: Record<AuditAction, string> = {
  CREATE: 'oluşturdu',
  UPDATE: 'güncelledi',
  DELETE: 'sildi',
  APPROVE: 'onayladı',
  REJECT: 'reddetti',
  EXPORT: 'dışa aktardı',
  LOGIN: 'giriş yaptı',
  LOGOUT: 'çıkış yaptı',
  OTHER: 'işlem yaptı',
};

/** Alan adı → iş dili etiketi. */
export const FIELD_LABELS: Record<string, string> = {
  amount: 'Tutar',
  assignedToId: 'Atanan kullanıcı',
  averageCost: 'Ortalama maliyet',
  bankAccountId: 'Banka hesabı',
  barcode: 'Barkod',
  cashAccountId: 'Kasa hesabı',
  categoryId: 'Kategori',
  code: 'Kod',
  contactId: 'Cari',
  createdById: 'Oluşturan',
  date: 'Tarih',
  description: 'Açıklama',
  discount: 'İskonto',
  dueDate: 'Vade tarihi',
  email: 'E-posta',
  fileName: 'Dosya adı',
  isActive: 'Aktiflik',
  method: 'Yöntem',
  minStockLevel: 'Kritik stok eşiği',
  name: 'Ad',
  notes: 'Not',
  number: 'Numara',
  ownerId: 'Sorumlu',
  paymentDate: 'Ödeme tarihi',
  percentage: 'Yüzde',
  priority: 'Öncelik',
  productId: 'Ürün',
  purchasePrice: 'Alış fiyatı',
  quantity: 'Miktar',
  reference: 'Referans',
  roleId: 'Rol',
  salesPrice: 'Satış fiyatı',
  status: 'Durum',
  subject: 'Konu',
  taxRate: 'Vergi oranı',
  taxRateId: 'Vergi',
  title: 'Başlık',
  totalGross: 'Genel toplam',
  totalNet: 'Ara toplam',
  totalTax: 'Vergi tutarı',
  type: 'Tip',
  unitPrice: 'Birim fiyat',
  updatedById: 'Güncelleyen',
  userId: 'Kullanıcı',
  validUntil: 'Geçerlilik tarihi',
  warehouseId: 'Depo',
};

/** Alan adı → formatlama türü. */
export const FIELD_KINDS: Record<string, AuditFieldKind> = {
  amount: 'money',
  assignedToId: 'reference',
  averageCost: 'money',
  bankAccountId: 'reference',
  cashAccountId: 'reference',
  categoryId: 'reference',
  contactId: 'reference',
  createdById: 'reference',
  date: 'date',
  discount: 'percent',
  dueDate: 'date',
  isActive: 'boolean',
  method: 'status',
  minStockLevel: 'quantity',
  ownerId: 'reference',
  paymentDate: 'date',
  percentage: 'percent',
  priority: 'status',
  productId: 'reference',
  purchasePrice: 'money',
  quantity: 'quantity',
  roleId: 'reference',
  salesPrice: 'money',
  status: 'status',
  taxRate: 'percent',
  taxRateId: 'reference',
  totalGross: 'money',
  totalNet: 'money',
  totalTax: 'money',
  type: 'status',
  unitPrice: 'money',
  updatedById: 'reference',
  userId: 'reference',
  validUntil: 'date',
  warehouseId: 'reference',
};

/** Enum değer → iş dili karşılığı. */
export const STATUS_LABELS: Record<string, string> = {
  ACCEPTED: 'Kabul edildi',
  ACTIVE: 'Aktif',
  APPROVED: 'Onaylandı',
  BANK_TRANSFER: 'Banka transferi',
  BOTH: 'Müşteri & Tedarikçi',
  CANCELLED: 'İptal',
  CASH: 'Nakit',
  CHECK: 'Çek',
  COMPLETED: 'Tamamlandı',
  CONFIRMED: 'Onaylandı',
  CREDIT_CARD: 'Kredi kartı',
  CRITICAL: 'Kritik',
  CUSTOMER: 'Müşteri',
  DELIVERED: 'Teslim edildi',
  DRAFT: 'Taslak',
  EXPIRED: 'Süresi doldu',
  FAILED: 'Başarısız',
  HIGH: 'Yüksek',
  IN_PROGRESS: 'Devam ediyor',
  LOW: 'Düşük',
  MEDIUM: 'Orta',
  OPEN: 'Açık',
  OVERDUE: 'Gecikmiş',
  PAID: 'Ödendi',
  PARTIALLY_DELIVERED: 'Kısmen teslim edildi',
  PARTIALLY_PAID: 'Kısmi ödeme',
  PENDING: 'Bekliyor',
  PROMISSORY_NOTE: 'Senet',
  PURCHASE: 'Alış',
  REJECTED: 'Reddedildi',
  RETURN_PURCHASE: 'İade alış',
  RETURN_SALES: 'İade satış',
  SALES: 'Satış',
  SENT: 'Gönderildi',
  SUPPLIER: 'Tedarikçi',
  WAITING_CUSTOMER: 'Müşteri bekliyor',
  WAITING_PARTS: 'Parça bekliyor',
};

/** Timeline'da önce gösterilecek önemli alanlar. */
export const IMPORTANT_FIELDS: readonly string[] = [
  'status',
  'amount',
  'totalGross',
  'minStockLevel',
  'salesPrice',
  'purchasePrice',
  'dueDate',
  'validUntil',
  'name',
  'number',
  'email',
  'priority',
  'contactId',
  'productId',
];

/** Audit log'da gizlenmesi gereken teknik alanlar. */
export const HIDDEN_FIELDS: ReadonlySet<string> = new Set([
  'id',
  'tenantId',
  'createdAt',
  'updatedAt',
  'deletedAt',
  'passwordHash',
  'keyHash',
  'sortOrder',
]);
