'use client';
import { AlertTriangle, BrainCircuit, Loader2, Play, ShieldCheck } from 'lucide-react';
import { formatCurrency } from '@/lib/utils';
import { useProcurementPlanning, useRunProcurementPlanning, useUpdateProcurementPolicy } from './use-procurement-planning';

export function ReplenishmentPlanningWorkspace() {
  const query = useProcurementPlanning(); const update = useUpdateProcurementPolicy(); const run = useRunProcurementPlanning();
  if (query.isLoading) return <div className="rounded-2xl border border-slate-800 p-6 text-sm text-slate-400"><Loader2 className="mr-2 inline h-4 w-4 animate-spin" />Talep ve ikmal senaryoları hesaplanıyor...</div>;
  if (!query.data) return <div className="rounded-2xl border border-rose-900/40 p-6 text-sm text-rose-300">Planlama verisi alınamadı.</div>;
  const workspace = query.data;
  return <section className="space-y-4 rounded-2xl border border-indigo-900/50 bg-slate-950/70 p-5">
    <div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-center"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-indigo-400"><BrainCircuit className="h-4 w-4" />Öngörülü stok ve satın alma</div><h2 className="mt-1 text-xl font-black text-white">İkmal karar merkezi</h2><p className="mt-1 text-xs text-slate-400">Gerçek tüketim, açık sipariş, mevsimsellik, tedarik süresi ve güvenilirlik tek kararda.</p></div><div className="flex gap-2"><button className="rounded-lg border border-slate-700 px-3 py-2 text-xs font-bold text-slate-200" onClick={() => update.mutate({ ...workspace.policy, autoCreateDrafts: !workspace.policy.autoCreateDrafts })}>{workspace.policy.autoCreateDrafts ? 'Otomatik taslak açık' : 'Otomatik taslak kapalı'}</button><button disabled={!workspace.policy.autoCreateDrafts || run.isPending} onClick={() => run.mutate()} className="rounded-lg bg-indigo-600 px-3 py-2 text-xs font-bold text-white disabled:opacity-40"><Play className="mr-1 inline h-3 w-3" />Onaylı politikayı çalıştır</button></div></div>
    <div className="grid grid-cols-2 gap-3 md:grid-cols-4">{[['Analiz', workspace.summary.productsAnalyzed], ['Aksiyon', workspace.summary.actionRequired], ['Kritik', workspace.summary.critical], ['Yatırım', formatCurrency(workspace.summary.recommendedInvestment)]].map(([label, value]) => <div key={label} className="rounded-xl border border-slate-800 bg-slate-900 p-3"><div className="text-[10px] uppercase text-slate-500">{label}</div><div className="mt-1 font-black text-white">{value}</div></div>)}</div>
    <div className="space-y-2">{workspace.recommendations.filter((item) => item.urgency !== 'HEALTHY').slice(0, 12).map((item) => { const selected = item.scenarios.find((candidate) => candidate.kind === item.recommendedScenario); return <article key={item.productId} className="grid gap-3 rounded-xl border border-slate-800 bg-slate-900/80 p-4 md:grid-cols-[1.3fr_1fr_1fr_auto] md:items-center"><div><div className="flex items-center gap-2 font-bold text-white">{item.urgency === 'CRITICAL' ? <AlertTriangle className="h-4 w-4 text-rose-400" /> : <ShieldCheck className="h-4 w-4 text-amber-400" />}{item.productName}</div><div className="text-[11px] text-slate-500">{item.productCode} · {item.supplierName ?? 'Tedarikçi gerekli'}</div></div><div className="text-xs text-slate-300"><b>{item.daysToStockout ?? '∞'}</b> gün stok ömrü<div className="text-[10px] text-slate-500">Günlük talep {item.dailyDemand}</div></div><div className="text-xs text-slate-300"><b>%{item.forecastAccuracy}</b> tahmin doğruluğu<div className="text-[10px] text-slate-500">Güvenlik stoğu {item.safetyStock}</div></div><div className="text-right text-xs"><div className="font-black text-indigo-300">{selected?.quantity ?? 0} adet</div><div className="text-slate-400">{formatCurrency(selected?.estimatedCost ?? 0)}</div></div></article>; })}</div>
  </section>;
}
