version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      # n8n ayarlari
      - N8N_RESTRICT_ENVIRONMENT_VARIABLES_ACCESS=false

      # Axon chatbot icin
      - N8N_SHARED_SECRET=axon-n8n-shared-secret-dev-2026
      - AXON_API_BASE_URL=http://host.docker.internal:3001
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
    external: true
