import type { CustomPriceRequest, PlanChangeQuote, PlanName, RevenueOverview, SubscriptionSnapshot } from '@repo/types';
import { adminApiClient } from '@/lib/admin-api-client';

const base = (tenantId: string) => `/api/admin/tenants/${encodeURIComponent(tenantId)}/subscription`;
export async function getRevenueOverview(): Promise<RevenueOverview> { return (await adminApiClient.get<{ data: RevenueOverview }>('/api/admin/revenue')).data.data; }
export async function getSubscription(tenantId: string): Promise<{ snapshot: SubscriptionSnapshot; customPrices: CustomPriceRequest[] }> { return (await adminApiClient.get<{ data: { snapshot: SubscriptionSnapshot; customPrices: CustomPriceRequest[] } }>(base(tenantId))).data.data; }
export async function quoteSubscriptionPlan(tenantId: string, toPlan: PlanName, effectiveAt: string): Promise<PlanChangeQuote> { return (await adminApiClient.post<{ data: PlanChangeQuote }>(`${base(tenantId)}/quote`, { toPlan, effectiveAt })).data.data; }
export async function reconcileSubscription(tenantId: string): Promise<SubscriptionSnapshot> { return (await adminApiClient.post<{ data: SubscriptionSnapshot }>(`${base(tenantId)}/reconcile`)).data.data; }
export async function applySubscriptionCoupon(tenantId: string, code: string): Promise<SubscriptionSnapshot> { return (await adminApiClient.post<{ data: SubscriptionSnapshot }>(`${base(tenantId)}/coupon`, { code })).data.data; }
export async function createSubscriptionCoupon(input: { code: string; percent: number; expiresAt: string; maxRedemptions?: number }): Promise<{ id: string; code: string }> { return (await adminApiClient.post<{ data: { id: string; code: string } }>('/api/admin/billing/coupons', input)).data.data; }
export async function requestSubscriptionPrice(tenantId: string, input: { monthlyAmount: number; unitPrice: number | null; expiresAt: string; reason: string }): Promise<CustomPriceRequest> { return (await adminApiClient.post<{ data: CustomPriceRequest }>(`${base(tenantId)}/custom-prices`, input)).data.data; }
export async function decideSubscriptionPrice(tenantId: string, requestId: string, decision: 'approve' | 'reject'): Promise<CustomPriceRequest> { return (await adminApiClient.post<{ data: CustomPriceRequest }>(`${base(tenantId)}/custom-prices/${encodeURIComponent(requestId)}/decision`, { decision })).data.data; }
export async function recordBillingEvent(input: { provider: 'MANUAL' | 'STRIPE' | 'IYZICO'; providerEventId: string; tenantId: string; type: 'SUBSCRIPTION_ACTIVE' | 'SUBSCRIPTION_CANCELED' | 'INVOICE_OPEN' | 'INVOICE_PAID' | 'INVOICE_FAILED'; providerInvoiceId?: string; amount?: number; currency: string; dueAt?: string; failureReason?: string }): Promise<void> { await adminApiClient.post('/api/admin/billing/provider-events', input); }
