import { NotFoundError } from '../../../../errors/index.js';
import type { AutomationScorecardRepository, ScorecardExecutionRecord } from './automation-scorecard.port.js';
import type { AutomationFeedbackInput, AutomationProcessMetric, AutomationScorecard } from './automation-scorecard.types.js';
const TARGET = 95; const DEFAULT_MINUTES = 5;
const pct = (part: number, total: number): number => total > 0 ? Math.round((part / total) * 1000) / 10 : 0;
function metric(process: string, rows: ScorecardExecutionRecord[], minutes: ReadonlyMap<string, number>): AutomationProcessMetric { const succeeded = rows.filter((row) => row.status === 'SUCCEEDED').length; const failed = rows.filter((row) => row.status === 'FAILED').length; const completed = succeeded + failed; return { process, executions: rows.length, succeeded, failed, successRatePct: pct(succeeded, completed), straightThroughRatePct: pct(rows.filter((row) => row.status === 'SUCCEEDED' && row.attempt === 1).length, completed), estimatedMinutesSaved: rows.filter((row) => row.status === 'SUCCEEDED').reduce((sum, row) => sum + (minutes.get(row.id) ?? DEFAULT_MINUTES), 0) }; }
export class AutomationScorecardService {
  constructor(private readonly repository: AutomationScorecardRepository) {}
  async get(tenantId: string, periodDays: number): Promise<AutomationScorecard> {
    const since = new Date(Date.now() - periodDays * 86_400_000); const [executions, feedback, recoveries] = await Promise.all([this.repository.listExecutions(tenantId, since), this.repository.listFeedback(tenantId, since), this.repository.countRecoveries(tenantId, since)]);
    const succeeded = executions.filter((row) => row.status === 'SUCCEEDED').length; const failed = executions.filter((row) => row.status === 'FAILED').length; const running = executions.filter((row) => row.status === 'RUNNING').length; const completed = succeeded + failed;
    const minutes = new Map(feedback.filter((row) => row.estimatedMinutesSaved !== null).map((row) => [row.executionId, row.estimatedMinutesSaved ?? 0])); const groups = new Map<string, ScorecardExecutionRecord[]>(); for (const row of executions) groups.set(row.process, [...(groups.get(row.process) ?? []), row]); const processes = [...groups].map(([name, rows]) => metric(name, rows, minutes)).sort((a, b) => b.executions - a.executions);
    const reasons = new Map<string, number>(); for (const row of feedback) if (row.reason) reasons.set(row.reason, (reasons.get(row.reason) ?? 0) + 1); const successRatePct = pct(succeeded, completed); const allowedFailures = Math.floor(completed * ((100 - TARGET) / 100));
    const reviewedIds = new Set(feedback.map((row) => row.executionId));
    return { periodDays, generatedAt: new Date().toISOString(), totals: { executions: executions.length, automaticallyCompleted: succeeded, failed, running, manualTouches: feedback.filter((row) => row.outcome !== 'ACCEPTED').length + executions.filter((row) => row.attempt > 1).length, recoveries, accepted: feedback.filter((row) => row.outcome === 'ACCEPTED').length, rejected: feedback.filter((row) => row.outcome === 'REJECTED').length, corrected: feedback.filter((row) => row.outcome === 'CORRECTED').length, straightThroughRatePct: pct(executions.filter((row) => row.status === 'SUCCEEDED' && row.attempt === 1).length, completed), successRatePct, estimatedHoursSaved: Math.round((processes.reduce((sum, row) => sum + row.estimatedMinutesSaved, 0) / 60) * 10) / 10, financialImpact: Math.round(feedback.reduce((sum, row) => sum + (row.financialImpact ?? 0), 0) * 100) / 100 }, errorBudget: { targetSuccessRatePct: TARGET, actualSuccessRatePct: successRatePct, remainingFailures: Math.max(0, allowedFailures - failed), breached: failed > allowedFailures }, processes, feedbackReasons: [...reasons].map(([reason, count]) => ({ reason, count })).sort((a, b) => b.count - a.count).slice(0, 8), backlog: executions.filter((row): row is ScorecardExecutionRecord & { status: 'RUNNING' | 'FAILED' } => row.status !== 'SUCCEEDED').slice(0, 20).map((row) => ({ executionId: row.id, process: row.process, status: row.status, startedAt: row.startedAt.toISOString(), error: row.error })), reviewQueue: executions.filter((row) => row.status === 'SUCCEEDED' && !reviewedIds.has(row.id)).slice(0, 20).map((row) => ({ executionId: row.id, process: row.process, startedAt: row.startedAt.toISOString() })) };
  }
  async feedback(tenantId: string, userId: string, executionId: string, input: AutomationFeedbackInput): Promise<{ recorded: true }> { if (!(await this.repository.executionExists(tenantId, executionId))) throw new NotFoundError('Otomasyon çalışması', executionId); await this.repository.saveFeedback(tenantId, userId, executionId, input); return { recorded: true }; }
}
