import assert from 'node:assert/strict';import{PrismaClient}from'@prisma/client';
const p=new PrismaClient(),base=process.env.API_URL??'http://localhost:3001',origin='http://localhost:3000',mark=`TEST_E2E_FIN_AUTO_${Date.now()}`;type S={cookie:string};
async function login(email:string,slug:string):Promise<S>{const r=await fetch(`${base}/api/auth/login`,{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify({email,password:'demo1234',tenantSlug:slug})});assert.equal(r.status,200);return{cookie:r.headers.get('set-cookie')!.split(';')[0]}}
async function api(s:S|null,path:string,method='GET',body?:unknown,raw?:string){const r=await fetch(`${base}/api/financial-autonomy${path}`,{method,headers:{origin,...(s?{cookie:s.cookie}:{}),...(body!==undefined||raw!==undefined?{'content-type':'application/json'}:{})},body:raw??(body===undefined?undefined:JSON.stringify(body))});return{status:r.status,body:await r.json().catch(()=>null)as any}}
async function fixture(slug:string,userId:string){const tenant=await p.tenant.create({data:{slug,companyName:mark,email:`${slug}@t.local`,plan:'ENTERPRISE',status:'ACTIVE',modules:['ACCOUNTING']}});await p.tenantUser.create({data:{tenantId:tenant.id,userId,isOwner:true}});const contact=await p.contact.create({data:{tenantId:tenant.id,type:'CUSTOMER',name:`${mark} Cari`,isActive:true}});const bank=await p.bankAccount.create({data:{tenantId:tenant.id,name:`${mark} Bank`}});const cash=await p.cashAccount.create({data:{tenantId:tenant.id,name:`${mark} Cash`}});const sales=await p.invoice.create({data:{tenantId:tenant.id,contactId:contact.id,type:'SALES',status:'PARTIALLY_PAID',number:`${mark}-S`,date:new Date('2026-08-01'),dueDate:new Date('2026-09-01'),totalNet:1000,totalGross:1000}});const purchase=await p.invoice.create({data:{tenantId:tenant.id,contactId:contact.id,type:'PURCHASE',status:'SENT',number:`${mark}-P`,date:new Date('2026-09-01'),dueDate:new Date('2026-10-10'),totalNet:300,totalGross:300}});const receive=await p.payment.create({data:{tenantId:tenant.id,contactId:contact.id,bankAccountId:bank.id,date:new Date(),amount:1000,method:'BANK_TRANSFER',direction:'RECEIVE',status:'COMPLETED'}});await p.paymentAllocation.create({data:{tenantId:tenant.id,paymentId:receive.id,invoiceId:sales.id,amount:400}});await p.payment.create({data:{tenantId:tenant.id,cashAccountId:cash.id,date:new Date(),amount:200,method:'CASH',direction:'SEND',status:'COMPLETED'}});await p.payment.create({data:{tenantId:tenant.id,cashAccountId:cash.id,date:new Date(),amount:500,method:'CASH',direction:'RECEIVE',status:'CANCELLED'}});return{tenant,contact,sales,purchase}}
async function main(){const admin=await p.user.findUniqueOrThrow({where:{email:'admin@axondemo.com'}}),a=await fixture(`${mark.toLowerCase()}-a`,admin.id),b=await fixture(`${mark.toLowerCase()}-b`,admin.id);try{const sa=await login(admin.email,a.tenant.slug),sb=await login(admin.email,b.tenant.slug),denied=await login('depo@axondemo.com','axon-demo');assert.equal((await api(null,'/cash-flow-forecast')).status,401);assert.equal((await api(denied,'/cash-flow-forecast')).status,403);for(const d of ['0','-1','1.5','abc','366'])assert.equal((await api(sa,`/cash-flow-forecast?days=${d}`)).status,400);
const forecast=await api(sa,'/cash-flow-forecast?days=30');assert.equal(forecast.status,200);assert.equal(forecast.body.data.initialBalance,800);assert.equal(forecast.body.data.totalExpectedInflow,600);assert.equal(forecast.body.data.totalExpectedOutflow,300);assert.equal(forecast.body.data.projectedEndBalance,1100);assert.equal(forecast.body.data.dailySnapshots.length,30);assert.equal(forecast.body.data.dailySnapshots.reduce((x:any,d:any)=>x+d.netFlow,0),300);
assert.equal((await api(sb,`/contact-velocity/${a.contact.id}`)).status,404);assert.equal((await api(sb,`/collection-settlement/${a.sales.id}`,'POST')).status,404);const draft=await api(sa,`/collection-settlement/${a.sales.id}`,'POST');assert.equal(draft.status,200);assert.equal(draft.body.data.totalAmount,600);assert.equal(draft.body.data.suggestedDiscountPercent,5);assert.equal(draft.body.data.discountAmount,30);assert.equal(draft.body.data.netPayableAmount,570);assert.equal(draft.body.data.installmentOptions.every((x:any)=>x.totalAmount===570),true);assert.equal((await api(sa,`/collection-settlement/${a.purchase.id}`,'POST')).status,400);
for(const body of [{},{actionType:'UNKNOWN'},{actionType:'TRIGGER_COLLECTION_SETTLEMENT',extra:true}])assert.equal((await api(sa,'/execute-action','POST',body)).status,400);assert.equal((await api(sa,'/execute-action','POST',undefined,'{')).status,400);const action=await api(sa,'/execute-action','POST',{actionType:'TRIGGER_COLLECTION_SETTLEMENT',payload:{invoiceId:a.sales.id,targetDiscountPct:3}});assert.equal(action.status,200);assert.equal(action.body.data.success,true);assert.equal(await p.auditLog.count({where:{tenantId:a.tenant.id,module:'accounting',entityId:a.sales.id}}),1);const foreignForecast=await api(sb,'/cash-flow-forecast?days=30');assert.equal(foreignForecast.body.data.initialBalance,800);console.log(JSON.stringify({status:'PASS',forecast:{initial:800,inflow:600,outflow:300,end:1100},settlement:{outstanding:600,discount:30,net:570},tenantIsolation:'PASS',audit:'PASS'}));}finally{await p.tenant.deleteMany({where:{id:{in:[a.tenant.id,b.tenant.id]}}});await p.$disconnect()}}
main().catch(e=>{console.error(e);process.exitCode=1});
