import assert from 'node:assert/strict';
import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient(), base = process.env.API_URL ?? 'http://localhost:3001', origin = 'http://localhost:3000', marker = `TEST_E2E_RECON_${Date.now()}`;
type Session = { cookie: string; tenantId: string };
async function login(email: string, slug: string): Promise<Session> { const r = await fetch(`${base}/api/auth/login`, { method: 'POST', headers: { origin, 'content-type': 'application/json' }, body: JSON.stringify({ email, password: 'demo1234', tenantSlug: slug }) }); assert.equal(r.status, 200); const b = await r.json() as any; return { cookie: r.headers.get('set-cookie')?.split(';')[0] ?? '', tenantId: b.data.tenant.id }; }
async function api(s: Session | null, path: string, method = 'GET', body?: unknown, raw?: string) { const r = await fetch(`${base}/api/reconciliations${path}`, { method, headers: { origin, ...(s ? { cookie: s.cookie } : {}), ...(body !== undefined || raw !== undefined ? { 'content-type': 'application/json' } : {}) }, body: raw ?? (body === undefined ? undefined : JSON.stringify(body)) }); return { status: r.status, body: await r.json().catch(() => null) as any }; }
async function fixture(slug: string, userId: string) { const tenant = await prisma.tenant.create({ data: { slug, companyName: marker, email: `${slug}@test.local`, plan: 'ENTERPRISE', status: 'ACTIVE', modules: ['ACCOUNTING'] } }); await prisma.tenantUser.create({ data: { tenantId: tenant.id, userId, isOwner: true } }); const account = await prisma.ledgerAccount.create({ data: { tenantId: tenant.id, code: '100', name: 'Kasa', accountType: 'ASSET' } }); const period = await prisma.fiscalPeriod.create({ data: { tenantId: tenant.id, name: marker, startDate: new Date('2041-01-01'), endDate: new Date('2041-12-31') } }); return { tenant, account, period }; }
async function main() {
  const admin = await prisma.user.findUniqueOrThrow({ where: { email: 'admin@axondemo.com' } }), a = await fixture(`${marker.toLowerCase()}-a`, admin.id), b = await fixture(`${marker.toLowerCase()}-b`, admin.id);
  try {
    const owner = await login(admin.email, a.tenant.slug), foreign = await login(admin.email, b.tenant.slug), denied = await login('depo@axondemo.com', 'axon-demo');
    assert.equal((await api(null, '')).status, 401); assert.equal((await api(denied, '')).status, 403); assert.equal((await api(denied, '', 'POST', { name: 'X', date: '2041-01-01' })).status, 403);
    for (const q of ['?page=0', '?page=x', '?limit=0', '?limit=101', '?isFinalized=x']) assert.equal((await api(owner, q)).status, 400);
    const bad = [{}, { name: ' ', date: '2041-01-01' }, { name: 'X'.repeat(201), date: '2041-01-01' }, { name: 'X', date: '2041-02-30' }, { name: 'X', date: '2041/01/01' }, { name: 'X', date: '2041-01-01', lines: [{ accountId: a.account.id, amount: 0 }] }, { name: 'X', date: '2041-01-01', lines: [{ accountId: a.account.id, amount: 1.001 }] }, { name: 'X', date: '2041-01-01', lines: [{ accountId: b.account.id, amount: 10 }] }];
    for (const body of bad) assert.equal((await api(owner, '', 'POST', body)).status, 400); assert.equal((await api(owner, '', 'POST', undefined, '{')).status, 400);
    const created = await api(owner, '', 'POST', { name: `${marker} Türkçe`, description: '  açıklama  ', date: '2041-06-01', lines: [{ accountId: a.account.id, amount: 100.25, notes: 'ilk' }] }); assert.equal(created.status, 201); const id = created.body.data.id; assert.equal(created.body.data.lines.length, 1);
    const db = await prisma.reconciliation.findUniqueOrThrow({ where: { id }, include: { lines: true } }); assert.equal(db.name, `${marker} Türkçe`); assert.equal(db.description, 'açıklama'); assert.equal(Number(db.lines[0].amount), 100.25);
    assert.equal((await api(owner, `/${id}`)).status, 200); assert.equal((await api(foreign, `/${id}`)).status, 404); assert.equal((await api(foreign, `/${id}/lines`, 'POST', { accountId: b.account.id, amount: 2 })).status, 404); assert.equal((await api(foreign, `/${id}/finalize`, 'POST')).status, 404);
    assert.equal((await api(owner, `/${id}/lines`, 'POST', { accountId: b.account.id, amount: 2 })).status, 400); assert.equal((await api(owner, `/${id}/lines`, 'POST', { accountId: a.account.id, amount: -20.5, refType: 'TEST', refId: '1' })).status, 201);
    const checklistBlocked = await fetch(`${base}/api/accounting/fiscal-periods/${a.period.id}/closing-checklist`, { headers: { origin, cookie: owner.cookie } }); assert.equal(checklistBlocked.status, 200); assert.equal(((await checklistBlocked.json()) as any).data.summary.canClose, false);
    const finals = await Promise.all([api(owner, `/${id}/finalize`, 'POST'), api(owner, `/${id}/finalize`, 'POST')]); assert.equal(finals.filter(x => x.status === 200).length, 1); assert.equal(finals.filter(x => x.status === 409).length, 1);
    const finalized = await prisma.reconciliation.findUniqueOrThrow({ where: { id } }); assert.equal(finalized.isFinalized, true); assert.ok(finalized.finalizedAt); assert.equal(finalized.finalizedById, admin.id); assert.equal((await api(owner, `/${id}/lines`, 'POST', { accountId: a.account.id, amount: 1 })).status, 400);
    assert.equal((await api(owner, '?isFinalized=true&page=1&limit=1')).body.meta.total, 1); assert.equal((await api(owner, '?isFinalized=false')).body.meta.total, 0);
    const checklistPass = await fetch(`${base}/api/accounting/fiscal-periods/${a.period.id}/closing-checklist`, { headers: { origin, cookie: owner.cookie } }); const item = ((await checklistPass.json()) as any).data.items.find((x: any) => x.key === 'reconciliations'); assert.equal(item.status, 'PASS');
    await prisma.fiscalPeriod.update({ where: { id: a.period.id }, data: { status: 'CLOSED', closedAt: new Date() } }); assert.equal((await api(owner, '', 'POST', { name: 'Closed', date: '2041-07-01', lines: [{ accountId: a.account.id, amount: 1 }] })).status, 400);
    await assert.rejects(prisma.reconciliationLine.create({ data: { tenantId: b.tenant.id, reconciliationId: id, accountId: b.account.id, amount: 1 } }));
    console.log('Reconciliations assurance PASS: auth, validation, CRUD lifecycle, concurrency, DB tenant FKs, period guard and closing checklist');
  } finally { await prisma.tenant.deleteMany({ where: { id: { in: [a.tenant.id, b.tenant.id] } } }); await prisma.$disconnect(); }
}
main().catch(e => { console.error(e); process.exitCode = 1; });
