import assert from 'node:assert/strict';
import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient(); const baseUrl = process.env.API_URL ?? 'http://localhost:3001'; const origin = 'http://localhost:3000'; const marker = `TEST_E2E_WC_${Date.now()}`;
type Session = { cookie: string; tenantId: string };
async function login(email: string, tenantSlug: string): Promise<Session> { const response = await fetch(`${baseUrl}/api/auth/login`, { method: 'POST', headers: { origin, 'content-type': 'application/json' }, body: JSON.stringify({ email, password: 'demo1234', tenantSlug }) }); assert.equal(response.status, 200); const body = await response.json() as any; return { cookie: response.headers.get('set-cookie')?.split(';')[0] ?? '', tenantId: body.data.tenant.id }; }
async function api(session: Session | null, path = '', method = 'GET', body?: unknown) { const response = await fetch(`${baseUrl}/api/production/work-centers${path}`, { method, headers: { origin, ...(session ? { cookie: session.cookie } : {}), ...(body !== undefined ? { 'content-type': 'application/json' } : {}) }, ...(body !== undefined ? { body: JSON.stringify(body) } : {}) }); return { status: response.status, body: await response.json().catch(() => null) as any }; }
async function main() {
  const owner = await login('admin@axondemo.com', 'axon-demo'); const unauthorized = await login('muhasebe@axondemo.com', 'axon-demo'); const foreign = await login('pro@axondemo.com', 'axon-pro-demo'); const ids: string[] = []; let bomId = ''; let productId = '';
  try {
    assert.equal((await api(null)).status, 401); assert.equal((await api(unauthorized)).status, 403); assert.equal((await api(owner, '?status=bad')).status, 400);
    for (const payload of [{}, { code: ' ', name: 'x' }, { code: 'x', name: ' ' }, { code: 'x', name: 'x', capacity: -1 }, { code: 'x', name: 'x', laborRate: -1 }, { code: 'x', name: 'x', overheadRate: 100_000_000 }]) assert.equal((await api(owner, '', 'POST', payload)).status, 400);
    const payload = { code: ` ${marker} `, name: ` ${marker} Türkçe Merkezi `, description: ' Açıklama ', capacity: 8.5, laborRate: 120, overheadRate: 30 };
    const concurrent = await Promise.all([api(owner, '', 'POST', payload), api(owner, '', 'POST', payload)]); assert.equal(concurrent.filter((r) => r.status === 201).length, 1); assert.equal(concurrent.filter((r) => r.status === 409).length, 1); const created = concurrent.find((r) => r.status === 201)!; const id = created.body.data.id as string; ids.push(id);
    const db = await prisma.workCenter.findUniqueOrThrow({ where: { id } }); assert.equal(db.code, marker); assert.equal(db.name, `${marker} Türkçe Merkezi`); assert.equal(db.description, 'Açıklama'); assert.equal(Number(db.capacity), 8.5); assert.equal(Number(db.laborRate), 120); assert.equal(Number(db.overheadRate), 30); assert.equal(await prisma.workCenter.count({ where: { tenantId: owner.tenantId, code: marker } }), 1);
    const listed = await api(owner, `?search=${encodeURIComponent('Türkçe')}&status=active&page=1&limit=1`); assert.equal(listed.status, 200); assert.equal(listed.body.meta.total, 1); assert.equal(listed.body.data[0].id, id);
    assert.equal((await api(owner, '/missing')).status, 404); assert.equal((await api(owner, '/missing/capacity')).status, 404); assert.equal((await api(foreign, `/${id}`)).status, 404); assert.equal((await api(foreign, `/${id}/capacity`)).status, 404); assert.equal([403, 404].includes((await api(foreign, `/${id}`, 'PATCH', { name: 'hack' })).status), true); assert.equal([403, 404].includes((await api(foreign, `/${id}`, 'DELETE')).status), true);
    assert.equal((await api(owner, `/${id}`, 'PATCH', { name: ' ' })).status, 400); assert.equal((await api(owner, `/${id}`, 'PATCH', { capacity: -1 })).status, 400); assert.equal((await api(owner, `/${id}`, 'PATCH', { isActive: 'yes' })).status, 400);
    const updated = await api(owner, `/${id}`, 'PATCH', { name: `${marker} Güncel`, capacity: 10, laborRate: 150, overheadRate: 50, isActive: false }); assert.equal(updated.status, 200); assert.equal(updated.body.data.name, `${marker} Güncel`); assert.equal(Number(updated.body.data.capacity), 10); assert.equal(updated.body.data.isActive, false);
    const passive = await api(owner, `?search=${encodeURIComponent(marker)}&status=passive`); assert.equal(passive.status, 200); assert.equal(passive.body.data.some((row: any) => row.id === id), true);
    await prisma.workCenterCapacity.createMany({ data: [{ tenantId: owner.tenantId, workCenterId: id, date: new Date('2026-10-02'), capacity: 10, allocated: 4 }, { tenantId: owner.tenantId, workCenterId: id, date: new Date('2026-10-01'), capacity: 10, allocated: 2 }] });
    const calendar = await api(owner, `/${id}/capacity`); assert.equal(calendar.status, 200); assert.equal(calendar.body.data.length, 2); assert.equal(calendar.body.data[0].date.slice(0, 10), '2026-10-01'); assert.equal(Number(calendar.body.data[0].capacity) - Number(calendar.body.data[0].allocated), 8); assert.equal((await api(owner, `/${id}`, 'DELETE')).status, 409);
    await prisma.workCenterCapacity.deleteMany({ where: { workCenterId: id } });
    const category = await prisma.category.findFirstOrThrow({ where: { tenantId: owner.tenantId } }); const unit = await prisma.unit.findFirstOrThrow({ where: { tenantId: owner.tenantId } }); const product = await prisma.product.create({ data: { tenantId: owner.tenantId, categoryId: category.id, unitId: unit.id, code: `${marker}_P`, name: marker } }); productId = product.id; const bom = await prisma.bOM.create({ data: { tenantId: owner.tenantId, productId, name: marker, version: '1.0', routings: { create: { tenantId: owner.tenantId, workCenterId: id, name: 'Kesim', stepOrder: 1, setupTime: 60, runTime: 30 } } } }); bomId = bom.id;
    assert.equal((await api(owner, `/${id}`, 'DELETE')).status, 409); assert.equal(await prisma.workCenter.count({ where: { id } }), 1); await prisma.bOM.delete({ where: { id: bomId } }); bomId = ''; await prisma.product.delete({ where: { id: productId } }); productId = '';
    const free = await api(owner, '', 'POST', { code: `${marker}_FREE`, name: 'Silinebilir', capacity: 0 }); assert.equal(free.status, 201); ids.push(free.body.data.id); assert.equal((await api(owner, `/${free.body.data.id}`, 'DELETE')).status, 200); assert.equal(await prisma.workCenter.count({ where: { id: free.body.data.id } }), 0);
    await prisma.workCenter.delete({ where: { id } }); ids.splice(ids.indexOf(id), 1);
    console.log('PASS work centers assurance: auth, tenant isolation, validation, concurrent uniqueness, CRUD, search/filter/pagination, capacity calendar and BOM delete protection');
  } finally { if (bomId) await prisma.bOM.deleteMany({ where: { id: bomId } }); if (productId) await prisma.product.deleteMany({ where: { id: productId } }); await prisma.workCenterCapacity.deleteMany({ where: { workCenterId: { in: ids } } }); await prisma.workCenter.deleteMany({ where: { id: { in: ids } } }); assert.equal(await prisma.workCenter.count({ where: { id: { in: ids } } }), 0); await prisma.$disconnect(); }
}
main().catch((error) => { console.error(error); process.exitCode = 1; });
