import assert from "node:assert/strict";
import { AccountType, FiscalPeriodStatus, PrismaClient } from "@prisma/client";
const prisma=new PrismaClient(),base=process.env.API_URL??"http://localhost:3001",origin="http://localhost:3000",marker=`TEST_E2E_PAYROLL_ACCOUNTING_${Date.now()}`;
type Session={cookie:string};
async function login(slug:string):Promise<Session>{const r=await fetch(`${base}/api/auth/login`,{method:"POST",headers:{origin,"content-type":"application/json"},body:JSON.stringify({email:"admin@axondemo.com",password:"demo1234",tenantSlug:slug})});assert.equal(r.status,200);return{cookie:r.headers.get("set-cookie")!.split(";")[0]};}
async function post(s:Session,path:string,body:unknown){const r=await fetch(`${base}${path}`,{method:"POST",headers:{origin,cookie:s.cookie,"content-type":"application/json"},body:JSON.stringify(body)});return{status:r.status,body:await r.json().catch(()=>null) as any};}
async function tenant(suffix:string,status?:FiscalPeriodStatus,withAccounts=true){const user=await prisma.user.findUniqueOrThrow({where:{email:"admin@axondemo.com"}});const t=await prisma.tenant.create({data:{slug:`${marker.toLowerCase()}-${suffix}`,companyName:marker,email:`${suffix}-${marker}@test.local`,plan:"ENTERPRISE",status:"ACTIVE",modules:["HR","PAYROLL","ACCOUNTING"]}});await prisma.tenantUser.create({data:{tenantId:t.id,userId:user.id,isOwner:true}});const e=await prisma.employee.create({data:{tenantId:t.id,firstName:"TEST_E2E",lastName:suffix,hireDate:new Date("2025-01-01"),salary:10000}});const p=await prisma.payroll.create({data:{tenantId:t.id,employeeId:e.id,period:"2026-09",grossSalary:10000,deductions:1000,netSalary:11000}});await prisma.payrollItem.createMany({data:[{tenantId:t.id,payrollId:p.id,label:"Addition",amount:2000,isDeduction:false},{tenantId:t.id,payrollId:p.id,label:"Deduction",amount:1000,isDeduction:true}]});if(withAccounts)await prisma.ledgerAccount.createMany({data:[{tenantId:t.id,code:"770",name:"Expense",accountType:AccountType.EXPENSE},{tenantId:t.id,code:"335",name:"Payable",accountType:AccountType.LIABILITY},{tenantId:t.id,code:"360",name:"Deductions",accountType:AccountType.LIABILITY}]});if(status)await prisma.fiscalPeriod.create({data:{tenantId:t.id,name:`2026-09 ${status}`,startDate:new Date("2026-09-01"),endDate:new Date("2026-09-30"),status}});return{t,e,p,s:await login(t.slug)};}
async function main(){const open=await tenant("open",FiscalPeriodStatus.OPEN),closed=await tenant("closed",FiscalPeriodStatus.CLOSED),locked=await tenant("locked",FiscalPeriodStatus.LOCKED),none=await tenant("none",undefined,false);try{const calls=await Promise.all([post(open.s,"/api/payroll/integration/accounting-voucher",{period:"2026-09"}),post(open.s,"/api/payroll/integration/accounting-voucher",{period:"2026-09"})]);assert.equal(calls.filter(x=>x.status===201).length,1);assert.equal(calls.filter(x=>[400,409].includes(x.status)).length,1);const success=calls.find(x=>x.status===201)!;const entries=await prisma.journalEntry.findMany({where:{tenantId:open.t.id,refType:"payroll",refId:"2026-09"},include:{lines:{include:{account:true}}}});assert.equal(entries.length,1);const entry=entries[0];assert.equal(entry.id,success.body.data.id);assert.equal(entry.fiscalPeriodId,(await prisma.fiscalPeriod.findFirstOrThrow({where:{tenantId:open.t.id}})).id);assert.equal(entry.isPosted,true);assert.ok(entry.lines.every(l=>l.tenantId===open.t.id&&l.account.tenantId===open.t.id));const debit=entry.lines.reduce((s,l)=>s+Number(l.debit),0),credit=entry.lines.reduce((s,l)=>s+Number(l.credit),0);assert.equal(debit,12000);assert.equal(credit,12000);assert.equal(debit,credit);assert.equal(success.body.data.totalGross,10000);assert.equal(success.body.data.totalNet,11000);assert.equal(success.body.data.totalDeductions,1000);assert.equal((await prisma.payroll.findUniqueOrThrow({where:{id:open.p.id}})).paidAt,null);
const originalLines=await prisma.journalEntryLine.count({where:{journalEntryId:entry.id}});assert.equal((await post(open.s,`/api/payroll/${open.p.id}/pay`,{})).status,200);assert.equal(await prisma.journalEntry.count({where:{tenantId:open.t.id,refType:"payroll",refId:"2026-09"}}),1);assert.equal(await prisma.journalEntryLine.count({where:{journalEntryId:entry.id}}),originalLines);assert.equal((await post(open.s,`/api/payroll/${open.p.id}/reverse`,{reason:"TEST_E2E accounting independence"})).status,200);assert.equal(await prisma.journalEntry.count({where:{id:entry.id}}),1);assert.equal(await prisma.journalEntryLine.count({where:{journalEntryId:entry.id}}),originalLines);
for(const fixture of [closed,locked,none]){const accountsBefore=await prisma.ledgerAccount.count({where:{tenantId:fixture.t.id}}),entriesBefore=await prisma.journalEntry.count({where:{tenantId:fixture.t.id}}),linesBefore=await prisma.journalEntryLine.count({where:{tenantId:fixture.t.id}});const result=await post(fixture.s,"/api/payroll/integration/accounting-voucher",{period:"2026-09"});assert.equal(result.status,400);assert.equal(await prisma.ledgerAccount.count({where:{tenantId:fixture.t.id}}),accountsBefore);assert.equal(await prisma.journalEntry.count({where:{tenantId:fixture.t.id}}),entriesBefore);assert.equal(await prisma.journalEntryLine.count({where:{tenantId:fixture.t.id}}),linesBefore);assert.equal((await prisma.payroll.findUniqueOrThrow({where:{id:fixture.p.id}})).paidAt,null);}
const foreignAccount=await prisma.ledgerAccount.findFirstOrThrow({where:{tenantId:closed.t.id}});await assert.rejects(()=>prisma.journalEntryLine.create({data:{tenantId:open.t.id,journalEntryId:entry.id,accountId:foreignAccount.id,debit:1,credit:0}}));await assert.rejects(()=>prisma.journalEntryLine.create({data:{tenantId:closed.t.id,journalEntryId:entry.id,accountId:foreignAccount.id,debit:1,credit:0}}));console.log(JSON.stringify({status:"PASS",journalEntryId:entry.id,refType:entry.refType,refId:entry.refId,debit,credit,balanced:debit===credit,concurrentStatuses:calls.map(x=>x.status),logicalVoucherCount:entries.length,failedPartialState:0,tenantIsolation:"PASS",paymentIndependent:"PASS",reversalAccountingBehavior:"UNCHANGED_BY_CONTRACT"}));}finally{await prisma.tenant.deleteMany({where:{companyName:marker}});assert.equal(await prisma.tenant.count({where:{companyName:marker}}),0);await prisma.$disconnect();}}
main().catch(async e=>{console.error(e);await prisma.$disconnect();process.exit(1)});
