import assert from "node:assert/strict";
import { PrismaClient } from "@prisma/client";
const prisma=new PrismaClient(),base=process.env.API_URL??"http://localhost:3001",origin="http://localhost:3000",marker=`TEST_E2E_MARKETPLACE_ORDER_${Date.now()}`;
type Session={cookie:string;tenantId:string};async function login(email:string,tenantSlug:string):Promise<Session>{const r=await fetch(`${base}/api/auth/login`,{method:"POST",headers:{origin,"content-type":"application/json"},body:JSON.stringify({email,password:"demo1234",tenantSlug})});assert.equal(r.status,200);const b=await r.json()as any;return{cookie:r.headers.get("set-cookie")?.split(";")[0]??"",tenantId:b.data.tenant.id}}async function api(s:Session|null,path:string,method="GET",body?:unknown){const r=await fetch(`${base}/api/marketplace${path}`,{method,headers:{origin,...(s?{cookie:s.cookie}:{}),...(body===undefined?{}:{"content-type":"application/json"})},body:body===undefined?undefined:JSON.stringify(body)});return{status:r.status,body:await r.json().catch(()=>null)as any}}
async function fixture(slug:string,userId:string){const t=await prisma.tenant.create({data:{slug,companyName:marker,email:`${slug}@test.local`,plan:"ENTERPRISE",status:"ACTIVE",modules:["MARKETPLACE","INVENTORY","SALES"]}});await prisma.tenantUser.create({data:{tenantId:t.id,userId,isOwner:true}});const unit=await prisma.unit.create({data:{tenantId:t.id,code:"AD",name:"Adet"}});const integration=await prisma.marketplaceIntegration.create({data:{tenantId:t.id,channel:"TRENDYOL",name:marker}});return{t,unit,integration}}
async function main(){const admin=await prisma.user.findUniqueOrThrow({where:{email:"admin@axondemo.com"}}),a=await fixture(`${marker.toLowerCase()}-a`,admin.id),b=await fixture(`${marker.toLowerCase()}-b`,admin.id);try{const owner=await login(admin.email,a.t.slug),foreign=await login(admin.email,b.t.slug),denied=await login("muhasebe@axondemo.com","axon-demo");assert.equal((await api(null,"/orders")).status,401);assert.equal((await api(denied,"/orders/missing/status","POST",{status:"PENDING"})).status,403);
 const product=await prisma.product.create({data:{tenantId:a.t.id,unitId:a.unit.id,code:`${marker}_P`,name:`${marker} Ürün`}});const order=await prisma.marketplaceOrder.create({data:{tenantId:a.t.id,integrationId:a.integration.id,externalId:`${marker}_1`,channel:"TRENDYOL",status:"PENDING",customerName:"TEST Müşteri",customerEmail:"test@example.com",totalAmount:240,orderDate:new Date(),items:{create:[{tenantId:a.t.id,externalProductId:"EXT-P",productId:product.id,name:product.name,quantity:2,unitPrice:120,lineTotal:240}]}}});const terminal=await prisma.marketplaceOrder.create({data:{tenantId:a.t.id,integrationId:a.integration.id,externalId:`${marker}_2`,channel:"TRENDYOL",status:"DELIVERED",totalAmount:50,orderDate:new Date(Date.now()-1000),items:{create:[{tenantId:a.t.id,externalProductId:"EXT-2",name:"Item",quantity:1,unitPrice:50,lineTotal:50}]}}});const foreignOrder=await prisma.marketplaceOrder.create({data:{tenantId:b.t.id,integrationId:b.integration.id,externalId:`${marker}_F`,channel:"TRENDYOL",status:"PENDING",totalAmount:999,orderDate:new Date()}});
 assert.equal((await api(owner,"/orders?status=INVALID")).status,400);assert.equal((await api(owner,"/orders?channel=INVALID")).status,400);const list=await api(owner,"/orders?page=1&limit=1&status=PENDING&channel=TRENDYOL");assert.equal(list.status,200);assert.equal(list.body.meta.total,1);assert.equal(list.body.meta.pageSize,1);assert.equal(list.body.data[0].id,order.id);assert.equal(list.body.data[0]._count.items,1);
 const detail=await api(owner,`/orders/${order.id}`);assert.equal(detail.status,200);assert.equal(detail.body.data.items.length,1);assert.equal(detail.body.data.items[0].product.id,product.id);assert.equal(Number(detail.body.data.totalAmount),detail.body.data.items.reduce((s:number,x:any)=>s+Number(x.lineTotal),0));assert.equal(Number(detail.body.data.items[0].lineTotal),detail.body.data.items[0].quantity*Number(detail.body.data.items[0].unitPrice));
 assert.equal((await api(foreign,`/orders/${order.id}`)).status,404);assert.equal((await api(foreign,`/orders/${order.id}/status`,"POST",{status:"DELIVERED"})).status,404);assert.equal((await api(foreign,`/orders/${order.id}`,"DELETE")).status,404);assert.equal((await api(owner,"/orders/missing")).status,404);
 for(const body of[null,{}, {status:"BAD"},{status:1}])assert.equal((await api(owner,`/orders/${order.id}/status`,"POST",body)).status,400,JSON.stringify(body));
 const changed=await api(owner,`/orders/${order.id}/status`,"POST",{status:"PROCESSING"});assert.equal(changed.status,200);assert.equal(changed.body.data.status,"PROCESSING");assert.equal((await prisma.marketplaceOrder.findUniqueOrThrow({where:{id:order.id}})).status,"PROCESSING");assert.equal(await prisma.auditLog.count({where:{tenantId:a.t.id,entityId:order.id,action:"UPDATE"}}),1);
 const retry=await Promise.all([api(owner,`/orders/${order.id}/status`,"POST",{status:"PROCESSING"}),api(owner,`/orders/${order.id}/status`,"POST",{status:"PROCESSING"})]);assert.deepEqual(retry.map(x=>x.status),[200,200]);assert.equal(await prisma.auditLog.count({where:{tenantId:a.t.id,entityId:order.id,action:"UPDATE"}}),1);
 assert.equal((await api(owner,`/orders/${order.id}`,"DELETE")).status,400);const removed=await api(owner,`/orders/${terminal.id}`,"DELETE");assert.equal(removed.status,200);assert.equal(await prisma.marketplaceOrder.count({where:{id:terminal.id}}),0);assert.equal(await prisma.marketplaceOrderItem.count({where:{marketplaceOrderId:terminal.id}}),0);assert.equal(await prisma.auditLog.count({where:{tenantId:a.t.id,entityId:terminal.id,action:"DELETE"}}),1);assert.equal((await prisma.marketplaceOrder.findUniqueOrThrow({where:{id:foreignOrder.id}})).totalAmount.toNumber(),999);
 console.log("PASS marketplace orders assurance: auth, filters, pagination, detail math, status validation/idempotency, audit, terminal delete, cascade and tenant isolation");
}finally{await prisma.tenant.deleteMany({where:{id:{in:[a.t.id,b.t.id]}}});assert.equal(await prisma.tenant.count({where:{companyName:marker}}),0);await prisma.$disconnect()}}main().catch(e=>{console.error(e);process.exitCode=1});
