import assert from "node:assert/strict";
import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient(), base = process.env.API_URL ?? "http://localhost:3001", origin = "http://localhost:3000", marker = `TEST_E2E_PAYROLL_${Date.now()}`;
type Session={cookie:string};
async function req(s:Session|null,path:string,method="GET",body?:unknown){const r=await fetch(`${base}${path}`,{method,headers:{origin,...(s?{cookie:s.cookie}:{}),...(body===undefined?{}:{"content-type":"application/json"})},body:body===undefined?undefined:JSON.stringify(body)});return{status:r.status,body:await r.json().catch(async()=>await r.text().catch(()=>null)),headers:r.headers};}
async function login(slug:string){const r=await fetch(`${base}/api/auth/login`,{method:"POST",headers:{origin,"content-type":"application/json"},body:JSON.stringify({email:"admin@axondemo.com",password:"demo1234",tenantSlug:slug})});assert.equal(r.status,200);return{cookie:r.headers.get("set-cookie")!.split(";")[0]};}
async function main(){const user=await prisma.user.findUniqueOrThrow({where:{email:"admin@axondemo.com"}});const make=async(s:string)=>{const t=await prisma.tenant.create({data:{slug:`${marker.toLowerCase()}-${s}`,companyName:marker,email:`${s}-${marker}@test.local`,plan:"ENTERPRISE",status:"ACTIVE",modules:["HR","PAYROLL","ACCOUNTING"]}});await prisma.tenantUser.create({data:{tenantId:t.id,userId:user.id,isOwner:true}});return t};const a=await make("a"),b=await make("b");try{const sa=await login(a.slug),sb=await login(b.slug);const ea=await prisma.employee.create({data:{tenantId:a.id,firstName:"TEST_E2E",lastName:"Payroll",hireDate:new Date("2025-01-01"),salary:10000}}),eb=await prisma.employee.create({data:{tenantId:b.id,firstName:"Foreign",lastName:"Payroll",hireDate:new Date("2025-01-01"),salary:10000}});
assert.equal((await req(null,"/api/payroll")).status,401);for(const q of ["page=0","limit=101","period=2026-13"])assert.equal((await req(sa,`/api/payroll?${q}`)).status,400);const valid={employeeId:ea.id,period:"2026-09",grossSalary:10000,items:[{label:"Prim",amount:2000,isDeduction:false},{label:"Kesinti",amount:1000,isDeduction:true}]};for(const p of [{}, {...valid,period:"2026-13"},{...valid,grossSalary:-1},{...valid,grossSalary:NaN},{...valid,items:[{label:"",amount:1,isDeduction:false}]},{...valid,items:[{label:"x",amount:-1,isDeduction:true}]},{...valid,unknown:true},{...valid,employeeId:eb.id}])assert.equal((await req(sa,"/api/payroll","POST",p)).status,400);
const concurrent=await Promise.all([req(sa,"/api/payroll","POST",valid),req(sa,"/api/payroll","POST",valid)]);assert.equal(concurrent.filter(x=>x.status===201).length,1);assert.equal(concurrent.filter(x=>x.status===409||x.status===400).length,1);const id=concurrent.find(x=>x.status===201)!.body.data.id;const db=await prisma.payroll.findUniqueOrThrow({where:{id},include:{items:true}});assert.equal(Number(db.deductions),1000);assert.equal(Number(db.netSalary),11000);assert.equal(db.items.length,2);assert.equal(await prisma.payroll.count({where:{tenantId:a.id,employeeId:ea.id,period:"2026-09"}}),1);
assert.equal((await req(sb,`/api/payroll/${id}`)).status,404);assert.equal((await req(sb,`/api/payroll/${id}/pay`,"POST",{})).status,404);assert.equal((await req(sa,`/api/payroll/${id}/items`,"POST",{label:"Ek",amount:500,isDeduction:false})).status,201);let detail=await req(sa,`/api/payroll/${id}`);assert.equal(Number(detail.body.data.netSalary),11500);const extra=detail.body.data.items.find((x:any)=>x.label==="Ek");assert.equal((await req(sa,`/api/payroll/${id}/items/${extra.id}`,"DELETE")).status,200);detail=await req(sa,`/api/payroll/${id}`);assert.equal(Number(detail.body.data.netSalary),11000);const pay=await Promise.all([req(sa,`/api/payroll/${id}/pay`,"POST",{}),req(sa,`/api/payroll/${id}/pay`,"POST",{})]);assert.deepEqual(pay.map(x=>x.status).sort(),[200,400]);assert.equal((await req(sa,`/api/payroll/${id}`,"DELETE")).status,400);assert.equal((await req(sa,`/api/payroll/${id}/reverse`,"POST",{reason:"TEST_E2E rollback"})).status,200);assert.equal((await req(sa,`/api/payroll/${id}`,"DELETE")).status,200);const deleted=await prisma.payroll.findUniqueOrThrow({where:{id}});assert.ok(deleted.deletedAt);
const restored=await req(sa,"/api/payroll","POST",valid);assert.equal(restored.status,201);assert.equal(restored.body.data.id,id);assert.equal(await prisma.payroll.count({where:{tenantId:a.id,employeeId:ea.id,period:"2026-09"}}),1);const accountsBefore=await prisma.ledgerAccount.count({where:{tenantId:a.id}});assert.equal((await req(sa,"/api/payroll/integration/accounting-voucher","POST",{period:"2026-09"})).status,400);assert.equal(await prisma.ledgerAccount.count({where:{tenantId:a.id}}),accountsBefore);const csv=await fetch(`${base}/api/payroll/integration/bank-file?period=2026-09`,{headers:{origin,cookie:sa.cookie}});assert.equal(csv.status,200);assert.match(await csv.text(),/TEST_E2E Payroll/);const checks=await req(sa,"/api/payroll/integration/closing-checks?period=2026-09");assert.equal(checks.status,200);assert.ok(Array.isArray(checks.body.data.checks));console.log("Payroll assurance PASS: validation, concurrency, calculations, lifecycle, tenant isolation, CSV, closing checks and DB consistency.");}finally{await prisma.tenant.deleteMany({where:{id:{in:[a.id,b.id]}}});assert.equal(await prisma.tenant.count({where:{companyName:marker}}),0);await prisma.$disconnect();}}
main().catch(async e=>{console.error(e);await prisma.$disconnect();process.exit(1)});
