import assert from 'node:assert/strict'; import { PrismaClient } from '@prisma/client';
const p=new PrismaClient(),base=process.env.API_URL??'http://localhost:3001',origin='http://localhost:3000',mark=`TEST_E2E_BANK_TX_${Date.now()}`; type S={cookie:string};
async function login(email:string,slug:string):Promise<S>{const r=await fetch(`${base}/api/auth/login`,{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify({email,password:'demo1234',tenantSlug:slug})});assert.equal(r.status,200);return{cookie:r.headers.get('set-cookie')!.split(';')[0]}}
async function api(s:S|null,path='',method='GET',body?:unknown,raw?:string){const r=await fetch(`${base}/api/bank-transactions${path}`,{method,headers:{origin,...(s?{cookie:s.cookie}:{}),...(body!==undefined||raw!==undefined?{'content-type':'application/json'}:{})},body:raw??(body===undefined?undefined:JSON.stringify(body))});return{status:r.status,body:await r.json().catch(()=>null) as any}}
async function fixture(slug:string,userId:string){const tenant=await p.tenant.create({data:{slug,companyName:mark,email:`${slug}@t.local`,plan:'ENTERPRISE',status:'ACTIVE',modules:['ACCOUNTING']}});await p.tenantUser.create({data:{tenantId:tenant.id,userId,isOwner:true}});const bank=await p.bankAccount.create({data:{tenantId:tenant.id,name:`${mark} Bank`}});const contact=await p.contact.create({data:{tenantId:tenant.id,type:'CUSTOMER',name:`${mark} Cari`,isActive:true}});const payment=await p.payment.create({data:{tenantId:tenant.id,contactId:contact.id,bankAccountId:bank.id,date:new Date('2026-10-01'),amount:100,method:'BANK_TRANSFER',direction:'RECEIVE',status:'COMPLETED',reference:mark}});return{tenant,bank,contact,payment}}
async function main(){const admin=await p.user.findUniqueOrThrow({where:{email:'admin@axondemo.com'}}),a=await fixture(`${mark.toLowerCase()}-a`,admin.id),b=await fixture(`${mark.toLowerCase()}-b`,admin.id);try{const sa=await login(admin.email,a.tenant.slug),sb=await login(admin.email,b.tenant.slug),denied=await login('depo@axondemo.com','axon-demo');assert.equal((await api(null)).status,401);assert.equal((await api(denied)).status,403);
const valid={bankAccountId:a.bank.id,type:'DEPOSIT',amount:100,balanceAfter:1100,date:'2026-10-01',description:`${mark} Türkçe ₺`,reference:mark};for(const bad of [{},{...valid,amount:0},{...valid,amount:-1},{...valid,amount:1.001},{...valid,amount:Infinity},{...valid,balanceAfter:NaN},{...valid,type:'BAD'},{...valid,date:'2026-02-30'},{...valid,description:'x'.repeat(501)},{...valid,unexpected:true}])assert.equal((await api(sa,'','POST',bad)).status,400);assert.equal((await api(sa,'','POST',undefined,'{')).status,400);assert.equal((await api(sa,'','POST',{...valid,bankAccountId:b.bank.id})).status,404);
const made=await api(sa,'','POST',valid);assert.equal(made.status,201);const id=made.body.data.id;const stored=await p.bankTransaction.findUniqueOrThrow({where:{id}});assert.equal(stored.tenantId,a.tenant.id);assert.equal(Number(stored.amount),100);assert.equal(Number(stored.balanceAfter),1100);
assert.equal((await api(sa,'?type=DEPOSIT&page=1&limit=1')).body.meta.total,1);assert.equal((await api(sa,'?type=WITHDRAWAL')).body.data.length,0);assert.equal((await api(sb)).body.data.some((x:any)=>x.id===id),false);assert.equal((await api(sb,`/${id}/match-suggestions`)).status,404);
for(const bad of [{},{refType:'BAD',refId:a.payment.id},{refType:'PAYMENT',refId:''},{refType:'PAYMENT',refId:a.payment.id,extra:true}])assert.equal((await api(sa,`/${id}/approve-match`,'POST',bad)).status,400);assert.equal((await api(sa,`/${id}/approve-match`,'POST',{refType:'PAYMENT',refId:b.payment.id})).status,404);const matched=await api(sa,`/${id}/approve-match`,'POST',{refType:'PAYMENT',refId:a.payment.id});assert.equal(matched.status,200);assert.deepEqual({refType:matched.body.data.refType,refId:matched.body.data.refId},{refType:'PAYMENT',refId:a.payment.id});
for(const body of [{transactionIds:[]},{transactionIds:['']},{transactionIds:[id],minConfidence:101},{transactionIds:[id],minConfidence:NaN},{transactionIds:[id],extra:true}])assert.equal((await api(sa,'/bulk-approve-matches','POST',body)).status,400);for(const body of [{minConfidence:-1},{limit:0},{limit:1.5},{limit:101},{extra:true}])assert.equal((await api(sa,'/auto-process-matches','POST',body)).status,400);assert.equal((await api(sa,'/auto-process-matches','POST',{minConfidence:95,limit:10})).status,200);
await assert.rejects(p.bankTransaction.create({data:{tenantId:a.tenant.id,bankAccountId:b.bank.id,type:'DEPOSIT',amount:1,balanceAfter:1,date:new Date()}}));console.log(JSON.stringify({status:'PASS',tenantIsolation:'PASS',matching:'PASS',filters:'PASS',dbCompositeFk:'PASS'}));}finally{await p.tenant.deleteMany({where:{id:{in:[a.tenant.id,b.tenant.id]}}});await p.$disconnect()}}
main().catch(e=>{console.error(e);process.exitCode=1});
