import assert from 'node:assert/strict'; import { PrismaClient } from '@prisma/client';
const p=new PrismaClient(),base=process.env.API_URL??'http://localhost:3001',origin='http://localhost:3000',mark=`TEST_E2E_PAYMENT_${Date.now()}`; type S={cookie:string;tenantId:string};
async function login(email:string,slug:string):Promise<S>{const r=await fetch(`${base}/api/auth/login`,{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify({email,password:'demo1234',tenantSlug:slug})});assert.equal(r.status,200);const b=await r.json() as any;return{cookie:r.headers.get('set-cookie')!.split(';')[0],tenantId:b.data.tenant.id}}
async function api(s:S|null,path:string,method='GET',body?:unknown,raw?:string){const r=await fetch(`${base}/api/payments${path}`,{method,headers:{origin,...(s?{cookie:s.cookie}:{}),...(body!==undefined||raw!==undefined?{'content-type':'application/json'}:{})},body:raw??(body===undefined?undefined:JSON.stringify(body))});return{status:r.status,body:await r.json().catch(()=>null) as any}}
async function fixture(slug:string,userId:string){const tenant=await p.tenant.create({data:{slug,companyName:mark,email:`${slug}@t.local`,plan:'ENTERPRISE',status:'ACTIVE',modules:['ACCOUNTING']}});await p.tenantUser.create({data:{tenantId:tenant.id,userId,isOwner:true}});const contact=await p.contact.create({data:{tenantId:tenant.id,type:'CUSTOMER',name:mark,isActive:true}});const bank=await p.bankAccount.create({data:{tenantId:tenant.id,name:`${mark} Bank`,currencyCode:'TRY'}});const cash=await p.cashAccount.create({data:{tenantId:tenant.id,name:`${mark} Cash`,currencyCode:'TRY'}});await p.fiscalPeriod.create({data:{tenantId:tenant.id,name:mark,startDate:new Date('2026-01-01'),endDate:new Date('2026-12-31')}});return{tenant,contact,bank,cash}}
async function invoice(tenantId:string,contactId:string,n:string,total:number){return p.invoice.create({data:{tenantId,contactId,type:'SALES',status:'SENT',number:n,date:new Date('2026-06-01'),totalNet:total,totalGross:total}})}
const pay=(contactId:string,invoiceId:string,amount:number,key:string,accountId?:string)=>({contactId,cashAccountId:accountId,date:'2026-06-15',amount,method:'CASH',direction:'RECEIVE',idempotencyKey:key,allocations:[{invoiceId,amount}]});
async function main(){const admin=await p.user.findUniqueOrThrow({where:{email:'admin@axondemo.com'}}),a=await fixture(`${mark.toLowerCase()}-a`,admin.id),b=await fixture(`${mark.toLowerCase()}-b`,admin.id);try{const s=await login(admin.email,a.tenant.slug),f=await login(admin.email,b.tenant.slug),denied=await login('depo@axondemo.com','axon-demo');assert.equal((await api(null,'')).status,401);assert.equal((await api(denied,'')).status,403);
const over=await invoice(a.tenant.id,a.contact.id,`${mark}-OVER`,1000);const rs=await Promise.all([api(s,'','POST',pay(a.contact.id,over.id,700,'over-a',a.cash.id)),api(s,'','POST',pay(a.contact.id,over.id,700,'over-b',a.cash.id))]);assert.equal(rs.filter(x=>x.status===201).length,1);assert.equal(rs.filter(x=>x.status>=400&&x.status<500).length,1);assert.equal(Number((await p.paymentAllocation.aggregate({where:{invoiceId:over.id},_sum:{amount:true}}))._sum.amount),700);
const exact=await invoice(a.tenant.id,a.contact.id,`${mark}-EXACT`,1000);const exactRs=await Promise.all([api(s,'','POST',pay(a.contact.id,exact.id,600,'exact-a',a.cash.id)),api(s,'','POST',pay(a.contact.id,exact.id,400,'exact-b',a.cash.id))]);assert.equal(exactRs.filter(x=>x.status===201).length,2);assert.equal(Number((await p.paymentAllocation.aggregate({where:{invoiceId:exact.id},_sum:{amount:true}}))._sum.amount),1000);assert.equal((await p.invoice.findUniqueOrThrow({where:{id:exact.id}})).status,'PAID');
const exactIds=exactRs.map(x=>x.body.data.id as string);assert.equal((await api(s,`/${exactIds[0]}/cancel`,'POST',{reason:'TEST full cancel first'})).status,200);assert.equal((await p.invoice.findUniqueOrThrow({where:{id:exact.id}})).status,'PARTIALLY_PAID');assert.equal((await api(s,`/${exactIds[1]}/cancel`,'POST',{reason:'TEST full cancel second'})).status,200);assert.equal((await p.invoice.findUniqueOrThrow({where:{id:exact.id}})).status,'SENT');assert.equal(await p.paymentAllocation.count({where:{invoiceId:exact.id}}),0);
const partial=await invoice(a.tenant.id,a.contact.id,`${mark}-PART`,2160);const made=await api(s,'','POST',pay(a.contact.id,partial.id,1000,'cancel-one',a.cash.id));assert.equal(made.status,201);const paymentId=made.body.data.id;assert.equal(Number((await p.paymentAllocation.aggregate({where:{invoiceId:partial.id},_sum:{amount:true}}))._sum.amount),1000);const before=await p.accountEntry.findMany({where:{refType:'PAYMENT',refId:paymentId}});assert.equal(before.length,1);const cancels=await Promise.all([api(s,`/${paymentId}/cancel`,'POST',{reason:'TEST cancel A'}),api(s,`/${paymentId}/cancel`,'POST',{reason:'TEST cancel B'})]);assert.equal(cancels.filter(x=>x.status===200).length,1);assert.equal(cancels.filter(x=>x.status>=400).length,1);assert.equal((await p.payment.findUniqueOrThrow({where:{id:paymentId}})).status,'CANCELLED');assert.equal(await p.paymentAllocation.count({where:{paymentId}}),0);const entries=await p.accountEntry.findMany({where:{refType:'PAYMENT',refId:paymentId}});assert.equal(entries.length,2);assert.equal(entries.reduce((x,e)=>x+Number(e.debit)-Number(e.credit),0),0);assert.equal((await p.invoice.findUniqueOrThrow({where:{id:partial.id}})).status,'SENT');
assert.equal((await api(s,'','POST',pay(a.contact.id,b.tenant.id,1,'foreign-invoice',a.cash.id))).status,400);assert.equal((await api(s,'','POST',{...pay(a.contact.id,over.id,1,'foreign-account'),cashAccountId:b.cash.id})).status,400);assert.equal((await api(f,`/${paymentId}`)).status,404);await assert.rejects(p.paymentAllocation.create({data:{tenantId:b.tenant.id,paymentId,invoiceId:over.id,amount:1}}));
const bankCreated=await api(s,'/bank-accounts','POST',{name:`${mark} Bank 2`,iban:'TR330006100519786457841326'});assert.equal(bankCreated.status,201);assert.equal((await api(s,`/bank-accounts/${bankCreated.body.data.id}`,'PATCH',{name:`${mark} Updated`})).status,200);assert.equal((await api(s,`/bank-accounts/${bankCreated.body.data.id}`,'DELETE')).status,200);assert.equal((await api(s,'','POST',{...pay(a.contact.id,over.id,1,'deleted-bank'),cashAccountId:undefined,bankAccountId:bankCreated.body.data.id})).status,400);assert.equal((await p.bankAccount.findUniqueOrThrow({where:{id:bankCreated.body.data.id}})).deletedAt!==null,true);
const cashCreated=await api(s,'/cash-accounts','POST',{name:`${mark} Cash 2`});assert.equal(cashCreated.status,201);assert.equal((await api(s,`/cash-accounts/${cashCreated.body.data.id}`,'PATCH',{name:`${mark} Cash Updated`})).status,200);assert.equal((await api(s,`/cash-accounts/${cashCreated.body.data.id}`,'DELETE')).status,200);assert.equal((await api(s,'','POST',{...pay(a.contact.id,over.id,1,'deleted-cash'),cashAccountId:cashCreated.body.data.id})).status,400);assert.equal((await p.cashAccount.findUniqueOrThrow({where:{id:cashCreated.body.data.id}})).deletedAt!==null,true);
for(const bad of [{},{date:'x',amount:1,method:'CASH'},{date:'2026-02-30',amount:1,method:'CASH'},{date:'2026-01-01',amount:0,method:'CASH'},{date:'2026-01-01',amount:-1,method:'CASH'},{date:'2026-01-01',amount:1.001,method:'CASH'},{date:'2026-01-01',amount:1,method:'BAD'}])assert.equal((await api(s,'','POST',bad)).status,400);assert.equal((await api(s,'','POST',undefined,'{')).status,400);
console.log(JSON.stringify({status:'PASS',concurrentOver:rs.map(x=>x.status),concurrentExact:exactRs.map(x=>x.status),concurrentCancel:cancels.map(x=>x.status),partial:{before:1000,remainingBefore:1160,after:0,remainingAfter:2160},accountEntryNet:0}));}finally{await p.tenant.deleteMany({where:{id:{in:[a.tenant.id,b.tenant.id]}}});await p.$disconnect()}}
main().catch(e=>{console.error(e);process.exitCode=1});
