import { expect,test,type Page } from "@playwright/test";
async function login(page:Page){await page.goto("/login");await page.getByLabel(/E-posta/).fill("admin@axondemo.com");await page.getByRole("textbox",{name:/ifre/,exact:true}).fill("demo1234");await page.getByRole("button",{name:/Giri.*Yap/}).click();await expect(page).toHaveURL(/\/dashboard$/)}
async function tenantId(){const r=await fetch("http://localhost:3001/api/auth/login",{method:"POST",headers:{origin:"http://localhost:3000","content-type":"application/json"},body:JSON.stringify({email:"admin@axondemo.com",password:"demo1234",tenantSlug:"axon-demo"})});return((await r.json())as any).data.tenant.id as string}
test("marketplace orders filters, refreshes, opens detail and changes status",async({page})=>{const tid=await tenantId();let status="PENDING";const calls:any[]=[];const base={id:"order-1",tenantId:tid,integrationId:"int-1",externalId:"TEST_E2E_ORDER",channel:"TRENDYOL",status,customerName:"TEST Müşteri",customerEmail:"test@example.com",customerPhone:null,shippingAddress:"Test adres",totalAmount:240,orderDate:"2026-10-02T08:00:00Z",syncedAt:"2026-10-02T08:00:00Z",updatedAt:"2026-10-02T08:00:00Z",integration:{id:"int-1",channel:"TRENDYOL",name:"TEST CHANNEL"},_count:{items:1}};
 await page.route("**/api/marketplace/orders**",async route=>{const req=route.request(),url=req.url();calls.push({method:req.method(),url,body:req.postData()});if(req.method()==="GET"&&url.endsWith("/orders/order-1"))return route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({data:{...base,status,items:[{id:"item-1",tenantId:tid,marketplaceOrderId:"order-1",externalProductId:"p",productId:"product-1",name:"TEST Ürün",quantity:2,unitPrice:120,lineTotal:240,product:{id:"product-1",code:"TEST-P",name:"TEST Ürün"}}]}})});if(req.method()==="GET")return route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({data:[{...base,status}],meta:{total:1,page:1,pageSize:20,totalPages:1}})});if(req.method()==="POST"&&url.endsWith("/status")){status="PROCESSING";return route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({data:{...base,status}})})}return route.fallback()});
 await login(page);await page.goto("/dashboard/marketplace/orders");await expect(page.getByText("TEST_E2E_ORDER")).toBeVisible();await expect(page.getByText(/₺240|240/).first()).toBeVisible();const before=calls.filter(x=>x.method==="GET").length;await page.getByRole("button",{name:/Yenile/}).click();await expect.poll(()=>calls.filter(x=>x.method==="GET").length).toBeGreaterThan(before);await page.getByRole("button",{name:"Bekliyor",exact:true}).click();await expect.poll(()=>calls.some(x=>x.url.includes("status=PENDING"))).toBe(true);
 await page.getByRole("button",{name:"Detay"}).click();await expect(page.getByRole("dialog",{name:/Sipariş TEST_E2E_ORDER/})).toBeVisible();await expect(page.getByText("TEST Ürün")).toBeVisible();await page.getByRole("button",{name:/Durum değiştir/}).click();const dialog=page.getByRole("dialog",{name:/Sipariş durumu değiştir/});await dialog.getByLabel("Yeni durum").selectOption("PROCESSING");await dialog.getByRole("button",{name:"Güncelle"}).click();await expect.poll(()=>calls.some(x=>x.method==="POST"&&x.body?.includes("PROCESSING"))).toBe(true);
});
test("marketplace orders exposes list failure with retry",async({page})=>{let requests=0;await page.route("**/api/marketplace/orders**",route=>{requests++;return route.fulfill({status:500,contentType:"application/json",body:JSON.stringify({error:{message:"controlled order failure"}})})});await login(page);await page.goto("/dashboard/marketplace/orders");await expect(page.getByRole("heading",{name:/lem tamamlanamad/})).toBeVisible();const before=requests;await page.getByRole("button",{name:/Tekrar dene/}).click();await expect.poll(()=>requests).toBeGreaterThan(before)});
