import { test, expect, type Page } from '@playwright/test';
async function login(page: Page) { await page.goto('/login'); await page.getByLabel(/E-posta/).fill('admin@axondemo.com'); await page.getByRole('textbox', { name: /ifre/, exact: true }).fill('demo1234'); await page.getByRole('button', { name: /Giri.*Yap/ }).click(); await expect(page).toHaveURL(/\/dashboard$/); }
const form = { id: 'wo:output', type: 'OUTPUT', status: 'blocked', workOrderId: 'wo', workOrderNumber: 'TEST_E2E_QUALITY_WO', product: { id: 'p', code: 'TEST-Q', name: 'TEST_E2E Quality Product' }, plannedQty: 100, producedQty: 90, completionPct: 90, checklist: [{ key: 'operation_completion', label: 'Operasyon kapanış kontrolü', passed: true, detail: '1/1 tamamlandı' }, { key: 'output_quantity', label: 'Çıktı miktar kontrolü', passed: false, detail: '90/100 üretildi' }, { key: 'scrap_review', label: 'Fire kontrolü', passed: false, detail: '10 fire' }] };
const data = { summary: { horizonDays: 30, inputFormCount: 0, outputFormCount: 1, blockedFormCount: 1, nonconformityCount: 1, criticalIssueCount: 1, correctiveActionCount: 1, failedCriteriaCount: 2, quarantineQuantity: 10, supplierQualityRiskCount: 1 }, inputForms: [], outputForms: [form], nonconformities: [{ id: 'issue', type: 'scrap', severity: 'critical', workOrderId: 'wo', workOrderNumber: 'TEST_E2E_QUALITY_WO', product: form.product, title: 'Fire kaydı', detail: '10 birim fire', quantityImpact: 10, detectedAt: '2026-09-30T00:00:00.000Z' }], correctiveActions: [{ id: 'action', source: 'task', status: 'in_progress', priority: 'critical', workOrderId: 'wo', workOrderNumber: 'TEST_E2E_QUALITY_WO', title: 'TEST_E2E CAPA', detail: 'Kök neden', dueAt: '2026-10-01T00:00:00.000Z' }], acceptanceCriteria: [{ key: 'scrap_review', label: 'Fire kontrolü', passedCount: 0, failedCount: 1, totalCount: 1, passRatePct: 0, status: 'failed' }], quarantineStock: [{ id: 'q', product: form.product, workOrderId: 'wo', workOrderNumber: 'TEST_E2E_QUALITY_WO', sourceIssueId: 'issue', sourceIssueTitle: 'Fire kaydı', quantity: 10, status: 'blocked', reason: '10 birim fire' }], supplierQualityScores: [{ supplier: { id: 's', code: 'TEST-S', name: 'TEST_E2E Supplier' }, qualityScore: 55, acceptanceRatePct: 60, returnRatePct: 20, totalOrders: 5, risk: 'high' }] };

test('quality control renders calculations and interactions', async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 1400 }); const requests: string[] = []; const consoleErrors: string[] = []; page.on('console', (message) => { if (message.type() === 'error') consoleErrors.push(message.text()); });
  await page.route('**/api/production/quality-control**', async (route) => { requests.push(route.request().url()); const horizon = Number(new URL(route.request().url()).searchParams.get('horizonDays') ?? 30); await route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ data: { ...data, summary: { ...data.summary, horizonDays: horizon } } }) }); });
  await login(page); await page.goto('/dashboard/production/quality-control'); await expect(page.getByRole('heading', { name: /Kalite Kontrol/ })).toBeVisible();
  await expect(page.getByText('Fire kaydı')).toBeVisible(); await expect(page.getByText('TEST_E2E CAPA')).toBeVisible(); await expect(page.getByText('10 AD', { exact: true })).toBeVisible(); await expect(page.getByText('TEST_E2E Supplier')).toBeVisible(); await expect(page.getByText('%90')).toBeVisible();
  await page.getByRole('combobox').selectOption('60'); await expect.poll(() => requests.some((url) => url.includes('horizonDays=60'))).toBe(true); const before = requests.length; await page.getByRole('button', { name: /Yenile/ }).click(); await expect.poll(() => requests.length).toBeGreaterThan(before);
  await page.reload(); await expect(page.getByText('Fire kaydı')).toBeVisible(); await page.goBack(); await page.goForward(); expect(consoleErrors).toEqual([]);
});

test('quality control exposes recoverable API error', async ({ page }) => {
  await page.route('**/api/production/quality-control**', (route) => route.fulfill({ status: 500, contentType: 'application/json', body: JSON.stringify({ error: { message: 'controlled' } }) })); await login(page); await page.goto('/dashboard/production/quality-control'); await expect(page.getByRole('heading', { name: /İşlem tamamlanamadı/ })).toBeVisible(); await expect(page.getByRole('button', { name: /Tekrar dene/ })).toBeVisible();
});
