import { test, expect, type Page } from '@playwright/test';
async function login(page: Page) { await page.goto('/login'); await page.getByLabel(/E-posta/).fill('admin@axondemo.com'); await page.getByRole('textbox', { name: /ifre/, exact: true }).fill('demo1234'); await page.getByRole('button', { name: /Giri.*Yap/ }).click(); await expect(page).toHaveURL(/\/dashboard$/); }
const center = { id: 'wc-1', code: 'TEST_E2E_WC_01', name: 'TEST Türkçe Merkezi', description: 'Montaj', capacity: 8.5, laborRate: 120, overheadRate: 30, isActive: true, createdAt: '2026-10-01T00:00:00.000Z', updatedAt: '2026-10-01T00:00:00.000Z', _count: { operations: 2, workOrderOps: 3 } };
test('work center list uses server filters and all row/modal actions', async ({ page }) => {
  const urls: string[] = []; const methods: string[] = [];
  await page.route('**/api/production/work-centers**', async (route) => { const request = route.request(); urls.push(request.url()); methods.push(request.method()); if (request.method() === 'GET') { const params = new URL(request.url()).searchParams; return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ data: [center], meta: { total: 51, page: Number(params.get('page') ?? 1), pageSize: 50, totalPages: 2 } }) }); } if (request.method() === 'DELETE') return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ data: { success: true } }) }); return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ data: { ...center, isActive: false } }) }); });
  await login(page); await page.goto('/dashboard/production/work-centers'); await expect(page.getByText('TEST Türkçe Merkezi')).toBeVisible(); await expect(page.getByText('8,5 saat', { exact: true })).toBeVisible(); await expect(page.getByRole('cell', { name: '2', exact: true })).toBeVisible();
  await page.getByLabel('İş merkezi ara').fill('Türkçe'); await expect.poll(() => urls.some((url) => url.includes('search=T%C3%BCrk%C3%A7e'))).toBe(true); await page.getByRole('button', { name: 'Aktif', exact: true }).click(); await expect.poll(() => urls.some((url) => url.includes('status=active'))).toBe(true); await page.getByRole('button', { name: 'Sonraki' }).click(); await expect.poll(() => urls.some((url) => url.includes('page=2'))).toBe(true); await page.getByRole('button', { name: /Temizle/ }).click(); await expect(page.getByLabel('İş merkezi ara')).toHaveValue('');
  await page.getByRole('button', { name: 'Yeni İş Merkezi' }).first().click(); await expect(page.getByRole('button', { name: 'Oluştur' })).toBeDisabled(); await page.getByLabel('Kod').fill('WC02'); await page.getByRole('textbox', { name: /^Ad/ }).fill('Yeni Merkez'); await page.getByLabel(/Günlük Kapasite/).fill('-1'); await page.getByRole('button', { name: 'İptal' }).click();
  await page.getByRole('button', { name: 'Düzenle' }).click(); await expect(page.getByRole('textbox', { name: /^Ad/ })).toHaveValue('TEST Türkçe Merkezi'); await page.getByRole('button', { name: 'İptal' }).click(); await page.getByRole('button', { name: 'Durum değiştir' }).click(); page.once('dialog', (dialog) => dialog.accept()); await page.getByRole('button', { name: 'Sil' }).click(); await expect.poll(() => methods.includes('PATCH') && methods.includes('DELETE')).toBe(true);
});
test('work center list exposes recoverable error', async ({ page }) => { await page.route('**/api/production/work-centers**', (route) => route.fulfill({ status: 500, contentType: 'application/json', body: JSON.stringify({ error: { message: 'controlled' } }) })); await login(page); await page.goto('/dashboard/production/work-centers'); await expect(page.getByRole('heading', { name: /İşlem tamamlanamadı/ })).toBeVisible(); await expect(page.getByRole('button', { name: /Tekrar dene/ })).toBeVisible(); });
