export type AutomationDomainTrigger = 'LOW_STOCK' | 'OVERDUE_INVOICE' | 'HIGH_VALUE_INVOICE' | 'LOW_MARGIN' | 'CHECK_DUE_SOON';
export type AutomationDomainAction = 'CREATE_TASK' | 'CREATE_NOTIFICATION' | 'DRAFT_REMINDER_EMAIL' | 'REQUEST_APPROVAL' | 'CREATE_PURCHASE_REQUEST_DRAFT';
