'use client';
import { useState } from 'react'; import { AlertTriangle, CheckCircle2, Clock3, Gauge, RotateCcw, Sparkles } from 'lucide-react'; import { Button } from '@/components/ui/Button'; import { cn } from '@/lib/utils'; import { useAutomationFeedback, useAutomationScorecard } from './use-automation-scorecard';
const periods = [7, 30, 90] as const;
export function AutomationScorecardPanel() {
  const [days, setDays] = useState<7 | 30 | 90>(30); const { data, isLoading, isError, refetch } = useAutomationScorecard(days); const feedback = useAutomationFeedback(days);
  if (isLoading) return <div className="rounded-2xl border border-slate-800 bg-slate-900/90 p-5 text-sm text-slate-400">Otomasyon skor kartı hazırlanıyor…</div>;
  if (isError || !data) return <div className="rounded-2xl border border-red-500/20 bg-red-500/5 p-5"><p className="text-sm text-red-300">Otomasyon skor kartı alınamadı.</p><Button className="mt-3" size="sm" variant="outline" onClick={() => void refetch()}>Tekrar dene</Button></div>;
  const cards = [{ label: 'Başarı oranı', value: `%${data.totals.successRatePct}`, icon: CheckCircle2 }, { label: 'Kesintisiz işlem', value: `%${data.totals.straightThroughRatePct}`, icon: Gauge }, { label: 'Tahmini zaman kazancı', value: `${data.totals.estimatedHoursSaved} sa`, icon: Clock3 }, { label: 'Manuel müdahale', value: String(data.totals.manualTouches), icon: RotateCcw }];
  return <section className="space-y-4 rounded-2xl border border-slate-800 bg-slate-900/90 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="flex items-center gap-2 font-bold text-white"><Sparkles className="h-5 w-5 text-violet-400" /> Tenant Otomasyon Skor Kartı</h3><p className="mt-1 text-xs text-slate-400">Kişileri değil süreç kalitesini, kazanımı ve müdahale ihtiyacını ölçer.</p></div><div className="flex rounded-lg border border-slate-700 p-1">{periods.map((period) => <button key={period} className={cn('rounded px-3 py-1 text-xs', days === period ? 'bg-violet-500 text-white' : 'text-slate-400')} onClick={() => setDays(period)}>{period} gün</button>)}</div></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{cards.map(({ label, value, icon: Icon }) => <div key={label} className="rounded-xl border border-slate-800 bg-slate-950/60 p-3"><div className="flex items-center justify-between text-xs text-slate-400"><span>{label}</span><Icon className="h-4 w-4" /></div><p className="mt-2 text-2xl font-black text-white">{value}</p></div>)}</div>
    <div className={cn('rounded-xl border p-3 text-xs', data.errorBudget.breached ? 'border-red-500/30 bg-red-500/5 text-red-300' : 'border-emerald-500/30 bg-emerald-500/5 text-emerald-300')}><AlertTriangle className="mr-2 inline h-4 w-4" />Hata bütçesi: hedef %{data.errorBudget.targetSuccessRatePct}, gerçekleşen %{data.errorBudget.actualSuccessRatePct}; {data.errorBudget.breached ? 'bütçe aşıldı' : `${data.errorBudget.remainingFailures} hata payı kaldı`}.</div>
    <div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="text-slate-500"><tr><th className="py-2">Süreç</th><th>Çalışma</th><th>Başarı</th><th>STP</th><th>Kazanç</th></tr></thead><tbody>{data.processes.map((row) => <tr key={row.process} className="border-t border-slate-800 text-slate-300"><td className="py-2 font-medium">{row.process}</td><td>{row.executions}</td><td>%{row.successRatePct}</td><td>%{row.straightThroughRatePct}</td><td>{row.estimatedMinutesSaved} dk</td></tr>)}</tbody></table>{data.processes.length === 0 && <p className="py-4 text-center text-slate-500">Bu dönemde otomasyon çalışması yok.</p>}</div>
    {data.reviewQueue.length > 0 && <div><h4 className="mb-2 text-xs font-semibold uppercase tracking-wide text-slate-400">Sonuç inceleme kuyruğu</h4><div className="space-y-2">{data.reviewQueue.slice(0, 5).map((item) => <div key={item.executionId} className="flex flex-wrap items-center justify-between gap-2 rounded-lg border border-slate-800 bg-slate-950/50 p-3"><div><p className="text-xs font-medium text-slate-200">{item.process}</p><p className="mt-1 text-[11px] text-slate-500">Başarılı otomasyon sonucu geri bildirim bekliyor.</p></div><div className="flex gap-1"><Button size="sm" variant="ghost" disabled={feedback.isPending} onClick={() => feedback.mutate({ executionId: item.executionId, outcome: 'ACCEPTED', reason: 'Sonuç beklendiği gibi' })}>Kabul et</Button><Button size="sm" variant="ghost" disabled={feedback.isPending} onClick={() => feedback.mutate({ executionId: item.executionId, outcome: 'CORRECTED', reason: 'Sonuç manuel düzeltildi' })}>Düzeltildi</Button></div></div>)}</div></div>}
    {data.backlog.length > 0 && <div><h4 className="mb-2 text-xs font-semibold uppercase tracking-wide text-slate-400">İyileştirme kuyruğu</h4><div className="space-y-2">{data.backlog.slice(0, 5).map((item) => <div key={item.executionId} className="flex flex-wrap items-center justify-between gap-2 rounded-lg border border-slate-800 bg-slate-950/50 p-3"><div><p className="text-xs font-medium text-slate-200">{item.process}</p><p className="mt-1 text-[11px] text-slate-500">{item.error ?? 'Çalışma henüz tamamlanmadı.'}</p></div><div className="flex gap-1"><Button size="sm" variant="ghost" disabled={feedback.isPending} onClick={() => feedback.mutate({ executionId: item.executionId, outcome: 'CORRECTED', reason: 'Manuel müdahale ile düzeltildi' })}>Düzeltildi</Button><Button size="sm" variant="ghost" disabled={feedback.isPending} onClick={() => feedback.mutate({ executionId: item.executionId, outcome: 'REJECTED', reason: 'Otomasyon sonucu uygun değildi' })}>Reddet</Button></div></div>)}</div></div>}
  </section>;
}
