"use client";

import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import type { CompleteRestoreDrillInput, CreateRestoreDrillInput, RecordBackupInput } from "@repo/types";
import { DatabaseBackup, RefreshCw, ShieldCheck } from "lucide-react";
import { canAdmin } from "@/lib/admin/permissions";
import { completeRestoreDrill, createRestoreDrill, getDisasterRecoveryOverview, recordBackup } from "@/services/disaster-recovery.service";
import { useAdminAuthStore } from "@/store/admin-auth.store";
import { toast } from "@/store/ui.store";

const panel = "rounded-2xl border border-slate-800 bg-slate-900/70 p-5";
const field = "rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-xs text-slate-200";
const button = "rounded-lg border border-slate-700 bg-slate-800 px-3 py-2 text-xs text-white disabled:opacity-40";
const initialBackup: RecordBackupInput = { providerRef: "", status: "SUCCESS", sizeBytes: "", encrypted: true, region: "", startedAt: "", completedAt: "" };
const initialDrill: CreateRestoreDrillInput = { backupId: "", environment: "dr-validation", runbookUrl: "", approvalId: "" };
const initialResult: CompleteRestoreDrillInput = { status: "PASSED", recoveryPointAt: "", actualRpoMinutes: 0, actualRtoMinutes: 0, notes: "" };
const date = (value: string | null) => value ? new Date(value).toLocaleString("tr-TR") : "—";
const bytes = (value: string) => `${(Number(value) / 1_073_741_824).toFixed(2)} GB`;

export function DisasterRecoveryPage() {
  const admin = useAdminAuthStore((state) => state.admin);
  const canManage = canAdmin(admin, "operations.manage");
  const client = useQueryClient();
  const [backup, setBackup] = useState(initialBackup);
  const [drill, setDrill] = useState(initialDrill);
  const [selectedDrillId, setSelectedDrillId] = useState("");
  const [result, setResult] = useState(initialResult);
  const query = useQuery({ queryKey: ["admin", "disaster-recovery"], queryFn: getDisasterRecoveryOverview });
  const refresh = async () => client.invalidateQueries({ queryKey: ["admin", "disaster-recovery"] });
  const backupMutation = useMutation({ mutationFn: () => recordBackup(backup), onSuccess: async () => { setBackup(initialBackup); await refresh(); toast.success("Yedek kanıtı kaydedildi."); } });
  const drillMutation = useMutation({ mutationFn: () => createRestoreDrill(drill), onSuccess: async () => { setDrill(initialDrill); await refresh(); toast.success("İzole restore tatbikatı başlatıldı."); } });
  const resultMutation = useMutation({ mutationFn: () => completeRestoreDrill(selectedDrillId, result), onSuccess: async () => { setSelectedDrillId(""); setResult(initialResult); await refresh(); toast.success("Restore tatbikatı doğrulandı."); } });
  const data = query.data;
  return <div className="space-y-5 pb-12">
    <header className="flex items-center justify-between"><div><h1 className="flex items-center gap-2 text-2xl font-semibold text-white"><DatabaseBackup className="text-sky-400" />Yedekleme ve Felaket Kurtarma</h1><p className="mt-1 text-xs text-slate-400">Yedek kanıtı, replikasyon sağlığı ve izole geri yükleme doğrulaması</p></div><button className={button} onClick={() => query.refetch()}><RefreshCw className="mr-1 inline h-4 w-4" />Yenile</button></header>
    {query.isError && <p role="alert" className="rounded-xl border border-rose-500/30 bg-rose-500/10 p-4 text-rose-200">Felaket kurtarma görünümü yüklenemedi.</p>}
    <div className="grid gap-3 md:grid-cols-4"><Metric label="Sağlık" value={data?.health ?? "—"} /><Metric label="Hedef RPO" value={`${data?.policy.targetRpoMinutes ?? 0} dk`} /><Metric label="Hedef RTO" value={`${data?.policy.targetRtoMinutes ?? 0} dk`} /><Metric label="Replikasyon sınırı" value={`${data?.policy.maxReplicationLagSeconds ?? 0} sn`} /></div>
    <div className="grid gap-4 lg:grid-cols-2"><section className={panel}><h2 className="font-semibold text-white">Son başarılı yedek</h2><Info backup={data?.lastSuccessfulBackup ?? null} /></section><section className={panel}><h2 className="font-semibold text-white">Son restore tatbikatı</h2><div className="mt-3 grid grid-cols-2 gap-2 text-xs text-slate-300"><span>Durum: {data?.lastRestoreDrill?.status ?? "—"}</span><span>Ortam: {data?.lastRestoreDrill?.environment ?? "—"}</span><span>RPO: {data?.lastRestoreDrill?.actualRpoMinutes ?? "—"} dk</span><span>RTO: {data?.lastRestoreDrill?.actualRtoMinutes ?? "—"} dk</span><span className="col-span-2">Tamamlanma: {date(data?.lastRestoreDrill?.completedAt ?? null)}</span></div></section></div>
    {canManage && <div className="grid gap-4 xl:grid-cols-2"><BackupForm value={backup} onChange={setBackup} onSubmit={() => backupMutation.mutate()} pending={backupMutation.isPending} /><DrillForm value={drill} backups={data?.backups.filter((item) => item.status === "SUCCESS" && item.encrypted) ?? []} onChange={setDrill} onSubmit={() => drillMutation.mutate()} pending={drillMutation.isPending} /><DrillResultForm drillId={selectedDrillId} value={result} drills={data?.restoreDrills.filter((item) => item.status === "RUNNING" || item.status === "PLANNED") ?? []} onDrillChange={setSelectedDrillId} onChange={setResult} onSubmit={() => resultMutation.mutate()} pending={resultMutation.isPending} /></div>}
    <section className={panel}><h2 className="font-semibold text-white">Yedek geçmişi</h2><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-xs text-slate-300"><thead className="text-slate-500"><tr><th>Ref</th><th>Durum</th><th>Boyut</th><th>Şifreli</th><th>Bölge / replika</th><th>Gecikme</th><th>Tamamlanma</th></tr></thead><tbody>{data?.backups.map((item) => <tr key={item.id} className="border-t border-slate-800"><td className="py-3">{item.providerRef}</td><td>{item.status}</td><td>{bytes(item.sizeBytes)}</td><td>{item.encrypted ? "Evet" : "Hayır"}</td><td>{item.region} / {item.replicaRegion ?? "—"}</td><td>{item.replicationLagSeconds ?? "—"} sn</td><td>{date(item.completedAt)}</td></tr>)}</tbody></table></div></section>
  </div>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className={panel}><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-xl font-semibold text-white">{value}</p></div>; }
function Info({ backup }: { backup: Awaited<ReturnType<typeof getDisasterRecoveryOverview>>["lastSuccessfulBackup"] }) { return <div className="mt-3 grid grid-cols-2 gap-2 text-xs text-slate-300"><span>Referans: {backup?.providerRef ?? "—"}</span><span>Boyut: {backup ? bytes(backup.sizeBytes) : "—"}</span><span>Şifreleme: {backup?.encrypted ? "Doğrulandı" : "—"}</span><span>Bölge: {backup?.region ?? "—"}</span><span>Replika: {backup?.replicaRegion ?? "—"}</span><span>Gecikme: {backup?.replicationLagSeconds ?? "—"} sn</span><span className="col-span-2">Tamamlanma: {date(backup?.completedAt ?? null)}</span></div>; }
function BackupForm({ value, onChange, onSubmit, pending }: { value: RecordBackupInput; onChange: (value: RecordBackupInput) => void; onSubmit: () => void; pending: boolean }) { return <section className={panel}><h2 className="font-semibold text-white">Yedek kanıtı kaydet</h2><div className="mt-3 grid gap-2 sm:grid-cols-2"><input className={field} placeholder="Provider referansı" value={value.providerRef} onChange={(e) => onChange({ ...value, providerRef: e.target.value })}/><input className={field} placeholder="Boyut (byte)" value={value.sizeBytes} onChange={(e) => onChange({ ...value, sizeBytes: e.target.value })}/><input className={field} placeholder="Ana bölge" value={value.region} onChange={(e) => onChange({ ...value, region: e.target.value })}/><input className={field} placeholder="Replika bölge" value={value.replicaRegion ?? ""} onChange={(e) => onChange({ ...value, replicaRegion: e.target.value || undefined })}/><input className={field} type="number" min={0} placeholder="Replikasyon gecikmesi (sn)" value={value.replicationLagSeconds ?? ""} onChange={(e) => onChange({ ...value, replicationLagSeconds: e.target.value ? Number(e.target.value) : undefined })}/><input className={field} placeholder="KMS anahtar referansı" value={value.encryptionKeyRef ?? ""} onChange={(e) => onChange({ ...value, encryptionKeyRef: e.target.value || undefined })}/><input className={field} type="datetime-local" value={value.startedAt} onChange={(e) => onChange({ ...value, startedAt: e.target.value })}/><input className={field} type="datetime-local" value={value.completedAt} onChange={(e) => onChange({ ...value, completedAt: e.target.value })}/><label className="flex items-center gap-2 text-xs text-slate-300"><input type="checkbox" checked={value.encrypted} onChange={(e) => onChange({ ...value, encrypted: e.target.checked })}/><ShieldCheck className="h-4 w-4"/>Şifreleme doğrulandı</label><button className={button} disabled={pending} onClick={onSubmit}>Kaydet</button></div></section>; }
function DrillForm({ value, backups, onChange, onSubmit, pending }: { value: CreateRestoreDrillInput; backups: Array<{ id: string; providerRef: string }>; onChange: (value: CreateRestoreDrillInput) => void; onSubmit: () => void; pending: boolean }) { return <section className={panel}><h2 className="font-semibold text-white">İzole restore tatbikatı</h2><p className="mt-1 text-xs text-amber-300">Production hedefleri reddedilir; onay kimliği ve runbook zorunludur.</p><div className="mt-3 grid gap-2"><select className={field} value={value.backupId} onChange={(e) => onChange({ ...value, backupId: e.target.value })}><option value="">Şifreli başarılı yedek seçin</option>{backups.map((item) => <option key={item.id} value={item.id}>{item.providerRef}</option>)}</select><input className={field} placeholder="İzole ortam" value={value.environment} onChange={(e) => onChange({ ...value, environment: e.target.value })}/><input className={field} placeholder="https://runbook..." value={value.runbookUrl} onChange={(e) => onChange({ ...value, runbookUrl: e.target.value })}/><input className={field} placeholder="Onay kimliği" value={value.approvalId} onChange={(e) => onChange({ ...value, approvalId: e.target.value })}/><button className={button} disabled={pending || !value.backupId} onClick={onSubmit}>Tatbikatı başlat</button></div></section>; }
function DrillResultForm({ drillId, value, drills, onDrillChange, onChange, onSubmit, pending }: { drillId: string; value: CompleteRestoreDrillInput; drills: Array<{ id: string; environment: string }>; onDrillChange: (id: string) => void; onChange: (value: CompleteRestoreDrillInput) => void; onSubmit: () => void; pending: boolean }) { return <section className={panel}><h2 className="font-semibold text-white">Tatbikat sonucunu doğrula</h2><div className="mt-3 grid gap-2 sm:grid-cols-2"><select className={field} value={drillId} onChange={(e) => onDrillChange(e.target.value)}><option value="">Çalışan tatbikatı seçin</option>{drills.map((item) => <option key={item.id} value={item.id}>{item.environment}</option>)}</select><select className={field} value={value.status} onChange={(e) => onChange({ ...value, status: e.target.value === "FAILED" ? "FAILED" : "PASSED" })}><option value="PASSED">Başarılı</option><option value="FAILED">Başarısız</option></select><input className={field} type="datetime-local" value={value.recoveryPointAt} onChange={(e) => onChange({ ...value, recoveryPointAt: e.target.value })}/><input className={field} type="number" min={0} placeholder="Gerçek RPO (dk)" value={value.actualRpoMinutes} onChange={(e) => onChange({ ...value, actualRpoMinutes: Number(e.target.value) })}/><input className={field} type="number" min={0} placeholder="Gerçek RTO (dk)" value={value.actualRtoMinutes} onChange={(e) => onChange({ ...value, actualRtoMinutes: Number(e.target.value) })}/><input className={field} placeholder="Doğrulama notu" value={value.notes} onChange={(e) => onChange({ ...value, notes: e.target.value })}/><button className={button} disabled={pending || !drillId} onClick={onSubmit}>Sonucu kaydet</button></div></section>; }
