import { AuditAction, EntityType, type Prisma, type PrismaClient } from '@prisma/client';
import { createAuditLog } from '../../../../utils/audit.js';
import type { AutomationFeedbackInput, AutomationFeedbackOutcome, AutomationScorecardRepository, ScorecardFeedbackRecord } from '../../application/automation-scorecard/index.js';
function objectValue(value: Prisma.JsonValue | null): Prisma.JsonObject | null { return value && typeof value === 'object' && !Array.isArray(value) ? value : null; }
function numberValue(value: Prisma.JsonValue | undefined): number | null { return typeof value === 'number' && Number.isFinite(value) ? value : null; }
function outcomeValue(value: Prisma.JsonValue | undefined): AutomationFeedbackOutcome | null { return value === 'ACCEPTED' || value === 'REJECTED' || value === 'CORRECTED' ? value : null; }
export class PrismaAutomationScorecardRepository implements AutomationScorecardRepository {
  constructor(private readonly db: PrismaClient) {}
  async listExecutions(tenantId: string, since: Date) { const rows = await this.db.automationExecution.findMany({ where: { tenantId, startedAt: { gte: since } }, select: { id: true, status: true, attempt: true, startedAt: true, error: true, rule: { select: { module: true } }, action: true }, orderBy: { startedAt: 'desc' } }); return rows.map((row) => ({ id: row.id, process: row.rule?.module ?? row.action ?? 'SYSTEM', status: row.status, attempt: row.attempt, startedAt: row.startedAt, error: row.error })); }
  async listFeedback(tenantId: string, since: Date): Promise<ScorecardFeedbackRecord[]> { const rows = await this.db.auditLog.findMany({ where: { tenantId, module: 'automation-scorecard', createdAt: { gte: since } }, select: { entityId: true, newValues: true }, orderBy: { createdAt: 'desc' } }); const result: ScorecardFeedbackRecord[] = []; const seen = new Set<string>(); for (const row of rows) { if (seen.has(row.entityId)) continue; const value = objectValue(row.newValues); const outcome = outcomeValue(value?.outcome); if (outcome) { seen.add(row.entityId); result.push({ executionId: row.entityId, outcome, reason: typeof value?.reason === 'string' ? value.reason : null, estimatedMinutesSaved: numberValue(value?.estimatedMinutesSaved), financialImpact: numberValue(value?.financialImpact) }); } } return result; }
  countRecoveries(tenantId: string, since: Date) { return this.db.auditLog.count({ where: { tenantId, module: 'recovery', createdAt: { gte: since } } }); }
  async executionExists(tenantId: string, executionId: string) { return (await this.db.automationExecution.count({ where: { tenantId, id: executionId } })) > 0; }
  async saveFeedback(tenantId: string, userId: string, executionId: string, input: AutomationFeedbackInput) { const newValues: Prisma.InputJsonObject = { outcome: input.outcome, reason: input.reason, estimatedMinutesSaved: input.estimatedMinutesSaved, financialImpact: input.financialImpact }; await createAuditLog(this.db, { tenantId, userId, module: 'automation-scorecard', entityType: EntityType.OTHER, entityId: executionId, action: AuditAction.UPDATE, newValues }); }
}
