ALTER TYPE "FeatureKey" ADD VALUE IF NOT EXISTS 'DOCUMENT_CENTER';
ALTER TYPE "FeatureKey" ADD VALUE IF NOT EXISTS 'SMART_NOTIFICATIONS';
ALTER TYPE "FeatureKey" ADD VALUE IF NOT EXISTS 'WORKFLOW_CENTER';
ALTER TYPE "FeatureKey" ADD VALUE IF NOT EXISTS 'MAIL_CENTER';
ALTER TYPE "FeatureKey" ADD VALUE IF NOT EXISTS 'BULK_OPERATIONS';
ALTER TYPE "FeatureKey" ADD VALUE IF NOT EXISTS 'CASHFLOW_FORECAST';
ALTER TYPE "FeatureKey" ADD VALUE IF NOT EXISTS 'BANK_RECONCILIATION';
ALTER TYPE "FeatureKey" ADD VALUE IF NOT EXISTS 'LOT_SERIAL_TRACKING';
