import { MODULE_KEY } from '@repo/types/plans';

export enum AppModule {
  ACCOUNTING = 'ACCOUNTING',
  INVENTORY = 'INVENTORY',
  CRM = 'CRM',
  SALES = 'SALES',
  PURCHASING = 'PURCHASING',
  WAREHOUSE = 'WAREHOUSE',
  PRODUCTION = 'PRODUCTION',
  SERVICE = 'SERVICE',
  HR = 'HR',
  PAYROLL = 'PAYROLL',
  MARKETPLACE = 'MARKETPLACE',
  REPORTING = 'REPORTING',
  CONTACTS = 'CONTACTS',
  INVOICING = 'INVOICING',
  APPROVALS = 'APPROVALS',
  MAIL = 'MAIL',
  WORKFLOW = 'WORKFLOW',
  DOCUMENTS = 'DOCUMENTS',
}

export const MODULE_KEYS = {
  ACCOUNTING: MODULE_KEY.ACCOUNTING,
  INVENTORY: MODULE_KEY.INVENTORY,
  CONTACTS: MODULE_KEY.CONTACTS,
  INVOICING: MODULE_KEY.INVOICING,
  REPORTING: MODULE_KEY.REPORTING,
  PURCHASING: MODULE_KEY.PURCHASING,
  PRODUCTION: MODULE_KEY.PRODUCTION,
  SERVICE: MODULE_KEY.SERVICE,
  MARKETPLACE: MODULE_KEY.MARKETPLACE,
  PAYROLL: MODULE_KEY.PAYROLL,
  HR: MODULE_KEY.HR,
  APPROVALS: MODULE_KEY.APPROVALS,
  WAREHOUSE: MODULE_KEY.WAREHOUSE,
  MAIL: MODULE_KEY.MAIL,
  WORKFLOW: MODULE_KEY.WORKFLOW,
  DOCUMENTS: MODULE_KEY.DOCUMENTS,
} as const;

export type ModuleKey = (typeof MODULE_KEYS)[keyof typeof MODULE_KEYS];

export interface ModuleAccessResult {
  module: ModuleKey;
  isActive: boolean;
  reason?: string;
}

export const APP_MODULE_TO_KEY: Record<AppModule, ModuleKey> = {
  [AppModule.ACCOUNTING]: MODULE_KEYS.ACCOUNTING,
  [AppModule.INVENTORY]: MODULE_KEYS.INVENTORY,
  [AppModule.CRM]: MODULE_KEYS.CONTACTS,
  [AppModule.SALES]: MODULE_KEYS.INVOICING,
  [AppModule.PURCHASING]: MODULE_KEYS.PURCHASING,
  [AppModule.WAREHOUSE]: MODULE_KEYS.WAREHOUSE,
  [AppModule.PRODUCTION]: MODULE_KEYS.PRODUCTION,
  [AppModule.SERVICE]: MODULE_KEYS.SERVICE,
  [AppModule.HR]: MODULE_KEYS.HR,
  [AppModule.PAYROLL]: MODULE_KEYS.PAYROLL,
  [AppModule.MARKETPLACE]: MODULE_KEYS.MARKETPLACE,
  [AppModule.REPORTING]: MODULE_KEYS.REPORTING,
  [AppModule.CONTACTS]: MODULE_KEYS.CONTACTS,
  [AppModule.INVOICING]: MODULE_KEYS.INVOICING,
  [AppModule.APPROVALS]: MODULE_KEYS.APPROVALS,
  [AppModule.MAIL]: MODULE_KEYS.MAIL,
  [AppModule.WORKFLOW]: MODULE_KEYS.WORKFLOW,
  [AppModule.DOCUMENTS]: MODULE_KEYS.DOCUMENTS,
};
