import { Prisma, type PrismaClient } from '@prisma/client';
import { ValidationError } from '../../../../errors/index.js';
import { parseProcessBlueprint, type BlueprintSection, type ProcessBlueprint, type ProcessBlueprintContent, type ProcessBlueprintRepository } from '../../application/process-blueprint/index.js';
const MODULE = 'process-blueprints'; const PREFIX = 'blueprint.'; const SENSITIVE = /(secret|token|password|credential|api[-_.]?key|private[-_.]?key)/i;
function jsonInput(value: unknown): Prisma.InputJsonValue | typeof Prisma.JsonNull { if (value === null || value === undefined) return Prisma.JsonNull; return JSON.parse(JSON.stringify(value)) as Prisma.InputJsonValue; }
export class PrismaProcessBlueprintRepository implements ProcessBlueprintRepository {
  constructor(private readonly db: PrismaClient) {}
  async snapshot(tenantId: string): Promise<ProcessBlueprintContent> {
    const [roles, numberSequences, approvalFlows, automationRules, moduleSettings] = await Promise.all([
      this.db.role.findMany({ where: { tenantId, isSystem: false }, include: { permissions: true }, orderBy: { name: 'asc' } }), this.db.numberSequence.findMany({ where: { tenantId }, orderBy: { module: 'asc' } }), this.db.approvalFlow.findMany({ where: { tenantId }, include: { steps: { include: { approverRole: { select: { name: true } } }, orderBy: { stepOrder: 'asc' } } }, orderBy: { name: 'asc' } }), this.db.automationRule.findMany({ where: { tenantId, deletedAt: null }, orderBy: { name: 'asc' } }), this.db.moduleSetting.findMany({ where: { tenantId, module: { not: MODULE } }, orderBy: [{ module: 'asc' }, { key: 'asc' }] }),
    ]);
    return { roles: roles.map((role) => ({ name: role.name, description: role.description, permissions: role.permissions.map(({ module, action }) => ({ module, action })) })), numberSequences: numberSequences.map(({ module, prefix, padding }) => ({ module, prefix, padding })), approvalFlows: approvalFlows.map((flow) => ({ name: flow.name, module: flow.module, isActive: flow.isActive, conditions: flow.conditions, steps: flow.steps.map((step) => ({ stepOrder: step.stepOrder, name: step.name, approverRoleName: step.approverRole?.name ?? null, isRequired: step.isRequired })) })), automationRules: automationRules.map((rule) => ({ name: rule.name, description: rule.description, trigger: rule.trigger, action: rule.action, module: rule.module, conditions: rule.conditions, actionConfig: rule.actionConfig, isActive: rule.isActive })), moduleSettings: moduleSettings.filter((setting) => !SENSITIVE.test(`${setting.module}.${setting.key}`)).map(({ module, key, value }) => ({ module, key, value })) };
  }
  async list(tenantId: string) { const rows = await this.db.moduleSetting.findMany({ where: { tenantId, module: MODULE, key: { startsWith: PREFIX } }, orderBy: { createdAt: 'desc' } }); return rows.flatMap((row) => { try { return [parseProcessBlueprint(JSON.parse(row.value))]; } catch { return []; } }); }
  async save(tenantId: string, blueprint: ProcessBlueprint) { const key = `${PREFIX}${blueprint.key}.v${blueprint.version}`; await this.db.moduleSetting.upsert({ where: { tenantId_module_key: { tenantId, module: MODULE, key } }, create: { tenantId, module: MODULE, key, value: JSON.stringify(blueprint) }, update: { value: JSON.stringify(blueprint) } }); }
  async apply(tenantId: string, blueprint: ProcessBlueprint, sections: readonly BlueprintSection[]) {
    await this.db.$transaction(async (tx) => {
      if (sections.includes('roles')) for (const item of blueprint.content.roles) {
        const protectedRole = await tx.role.findFirst({ where: { tenantId, name: item.name, isSystem: true }, select: { id: true } });
        if (protectedRole) throw new ValidationError(`Sistem rolü süreç paketiyle değiştirilemez: ${item.name}`);
        const role = await tx.role.upsert({ where: { tenantId_name: { tenantId, name: item.name } }, create: { tenantId, name: item.name, description: item.description }, update: { description: item.description } });
        await tx.rolePermission.deleteMany({ where: { roleId: role.id } });
        if (item.permissions.length) await tx.rolePermission.createMany({ data: item.permissions.map((permission) => ({ roleId: role.id, ...permission })), skipDuplicates: true });
      }
      if (sections.includes('numberSequences')) for (const item of blueprint.content.numberSequences) await tx.numberSequence.upsert({ where: { tenantId_module: { tenantId, module: item.module } }, create: { tenantId, ...item, lastNum: 0 }, update: { prefix: item.prefix, padding: item.padding } });
      if (sections.includes('approvalFlows')) for (const item of blueprint.content.approvalFlows) { const flow = await tx.approvalFlow.upsert({ where: { tenantId_module_name: { tenantId, module: item.module, name: item.name } }, create: { tenantId, name: item.name, module: item.module, conditions: jsonInput(item.conditions), isActive: item.isActive }, update: { conditions: jsonInput(item.conditions), isActive: item.isActive } }); await tx.approvalStep.deleteMany({ where: { flowId: flow.id } }); for (const step of item.steps) { const role = step.approverRoleName ? await tx.role.findUnique({ where: { tenantId_name: { tenantId, name: step.approverRoleName } }, select: { id: true } }) : null; await tx.approvalStep.create({ data: { flowId: flow.id, stepOrder: step.stepOrder, name: step.name, approverRoleId: role?.id ?? null, isRequired: step.isRequired } }); } }
      if (sections.includes('automationRules')) for (const item of blueprint.content.automationRules) await tx.automationRule.upsert({ where: { tenantId_name: { tenantId, name: item.name } }, create: { tenantId, ...item, conditions: jsonInput(item.conditions), actionConfig: jsonInput(item.actionConfig) }, update: { description: item.description, trigger: item.trigger, action: item.action, module: item.module, conditions: jsonInput(item.conditions), actionConfig: jsonInput(item.actionConfig), isActive: item.isActive, deletedAt: null } });
      if (sections.includes('moduleSettings')) for (const item of blueprint.content.moduleSettings.filter((setting) => !SENSITIVE.test(`${setting.module}.${setting.key}`))) await tx.moduleSetting.upsert({ where: { tenantId_module_key: { tenantId, module: item.module, key: item.key } }, create: { tenantId, ...item }, update: { value: item.value } });
    });
  }
}
