'use client';
import { useRef, useState } from 'react'; import { Download, PackageCheck, Upload } from 'lucide-react'; import { Button } from '@/components/ui/Button'; import { Modal } from '@/components/ui/Modal'; import { exportBlueprint } from './process-blueprint.api'; import { ProcessBlueprintSchema, type BlueprintSection, type ProcessBlueprint } from './process-blueprint.schemas'; import { useApplyBlueprint, useCreateBlueprint, useImportBlueprint, usePreviewBlueprint, useProcessBlueprints, useSectorBlueprints } from './use-process-blueprints'; import { toast } from '@/store/ui.store';
const sections: Array<{ key: BlueprintSection; label: string }> = [{ key: 'roles', label: 'Roller ve menüler' }, { key: 'numberSequences', label: 'Numara serileri' }, { key: 'approvalFlows', label: 'Onay akışları' }, { key: 'automationRules', label: 'Otomasyonlar' }, { key: 'moduleSettings', label: 'Form ve rapor ayarları' }];
export function ProcessBlueprintPanel() {
  const { data = [] } = useProcessBlueprints(); const { data: sectors = [] } = useSectorBlueprints(); const create = useCreateBlueprint(); const importer = useImportBlueprint(); const preview = usePreviewBlueprint(); const apply = useApplyBlueprint(); const fileRef = useRef<HTMLInputElement>(null); const [name, setName] = useState(''); const [selected, setSelected] = useState<BlueprintSection[]>(sections.map((item) => item.key)); const [active, setActive] = useState<ProcessBlueprint | null>(null);
  const load = async (key: string, version: number) => { const blueprint = await exportBlueprint(key, version); setActive(blueprint); preview.mutate({ blueprint, sections: selected }); };
  const download = async (key: string, version: number) => { const blueprint = await exportBlueprint(key, version); const url = URL.createObjectURL(new Blob([JSON.stringify(blueprint, null, 2)], { type: 'application/json' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `${key}-v${blueprint.version}.json`; anchor.click(); URL.revokeObjectURL(url); };
  const readFile = async (file: File) => { try { const blueprint = ProcessBlueprintSchema.parse(JSON.parse(await file.text())); await importer.mutateAsync(blueprint); } catch { toast.error('Süreç paketi dosyası geçersiz.'); } };
  return <section className="rounded-2xl border border-slate-800 bg-slate-900/80 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="flex items-center gap-2 font-semibold text-white"><PackageCheck className="h-5 w-5 text-cyan-400" /> Süreç Paketleri</h3><p className="mt-1 text-xs text-slate-400">Onaylı tenant konfigürasyonunu sürümleyin, karşılaştırın ve seçerek taşıyın.</p></div><div className="flex gap-2"><input ref={fileRef} type="file" accept="application/json" className="hidden" onChange={(event) => { const file = event.target.files?.[0]; if (file) void readFile(file); event.target.value = ''; }} /><Button size="sm" variant="outline" leftIcon={<Upload className="h-4 w-4" />} onClick={() => fileRef.current?.click()}>İçe aktar</Button></div></div>
    <div className="mt-4 flex flex-wrap gap-2"><input value={name} onChange={(event) => setName(event.target.value)} placeholder="Paket adı" className="h-9 min-w-52 rounded-lg border border-slate-700 bg-slate-950 px-3 text-sm text-white" /><Button size="sm" loading={create.isPending} disabled={!name.trim()} onClick={() => create.mutate({ key: name, name }, { onSuccess: () => setName('') })}>Mevcut yapıyı sürümle</Button>{sectors.map((item) => <Button key={item.key} size="sm" variant="ghost" onClick={() => { setActive(item); preview.mutate({ blueprint: item, sections: selected }); }}>{item.name}</Button>)}</div>
    <div className="mt-3 flex flex-wrap gap-3">{sections.map((item) => <label key={item.key} className="flex items-center gap-2 text-xs text-slate-300"><input type="checkbox" checked={selected.includes(item.key)} onChange={(event) => setSelected((current) => event.target.checked ? [...current, item.key] : current.filter((key) => key !== item.key))} />{item.label}</label>)}</div>
    <div className="mt-4 grid gap-2 md:grid-cols-2">{data.map((item) => <div key={`${item.key}-${item.version}`} className="flex items-center justify-between rounded-lg border border-slate-800 bg-slate-950/50 p-3"><div><p className="text-sm font-medium text-slate-200">{item.name} <span className="text-slate-500">v{item.version}</span></p><p className="text-[11px] text-slate-500">{Object.values(item.counts).reduce((sum, count) => sum + count, 0)} konfigürasyon öğesi</p></div><div className="flex"><Button size="sm" variant="ghost" onClick={() => void load(item.key, item.version)}>Fark</Button><Button size="sm" variant="ghost" onClick={() => void download(item.key, item.version)}><Download className="h-4 w-4" /></Button></div></div>)}</div>
    <Modal isOpen={active !== null} onClose={() => { setActive(null); preview.reset(); }} title="Dry-run fark raporu" description={active ? `${active.name} v${active.version}` : ''} footer={<><Button variant="ghost" onClick={() => setActive(null)}>Kapat</Button><Button disabled={!active || !selected.length} loading={apply.isPending} onClick={() => active && apply.mutate({ blueprint: active, sections: selected }, { onSuccess: () => setActive(null) })}>Seçili bölümleri uygula</Button></>}><div className="space-y-2">{preview.isPending && <p className="text-sm text-slate-400">Farklar hesaplanıyor…</p>}{preview.data && <><p className="text-sm text-slate-300">{preview.data.changes} değişiklik uygulanacak.</p>{preview.data.differences.slice(0, 30).map((item) => <div key={`${item.section}-${item.key}`} className="flex justify-between rounded border border-slate-800 p-2 text-xs"><span className="text-slate-300">{item.key}</span><span className={item.action === 'UNCHANGED' ? 'text-slate-500' : item.action === 'CREATE' ? 'text-emerald-400' : 'text-amber-400'}>{item.action}</span></div>)}</>}</div></Modal>
  </section>;
}
