import { z } from 'zod'; import { apiClient } from '@/lib/api-client'; import { safeParse } from '@/lib/safe-parse'; import { BlueprintPreviewSchema, BlueprintSummarySchema, ProcessBlueprintSchema, type BlueprintSection, type ProcessBlueprint } from './process-blueprint.schemas';
const base = '/api/process-blueprints';
export async function listBlueprints() { const response = await apiClient.get(base); return safeParse(z.array(BlueprintSummarySchema), response.data.data, 'listBlueprints'); }
export async function listSectorBlueprints() { const response = await apiClient.get(`${base}/sectors`); return safeParse(z.array(ProcessBlueprintSchema), response.data.data, 'listSectorBlueprints'); }
export async function createBlueprint(input: { key: string; name: string; description?: string; industry?: string }) { const response = await apiClient.post(base, input); return safeParse(ProcessBlueprintSchema, response.data.data, 'createBlueprint'); }
export async function exportBlueprint(key: string, version?: number) { const response = await apiClient.get(`${base}/${encodeURIComponent(key)}/export`, { params: version === undefined ? undefined : { version } }); return safeParse(ProcessBlueprintSchema, response.data.data, 'exportBlueprint'); }
export async function importBlueprint(blueprint: ProcessBlueprint) { const response = await apiClient.post(`${base}/import`, blueprint); return safeParse(ProcessBlueprintSchema, response.data.data, 'importBlueprint'); }
export async function previewBlueprint(blueprint: ProcessBlueprint, sections: BlueprintSection[]) { const response = await apiClient.post(`${base}/preview`, { blueprint, sections }); return safeParse(BlueprintPreviewSchema, response.data.data, 'previewBlueprint'); }
export async function applyBlueprint(blueprint: ProcessBlueprint, sections: BlueprintSection[]) { const response = await apiClient.post(`${base}/apply`, { blueprint, sections }); return safeParse(BlueprintPreviewSchema, response.data.data, 'applyBlueprint'); }
