import { Hono } from 'hono';
import { FeatureKey } from '@prisma/client';
import { requireFeature } from '../../../../middleware/requireFeature.js';
import { ChatController } from './chat.controller.js';
import { ChatUploadController } from './chat-upload.controller.js';

export const chatRoutes = new Hono();
chatRoutes.use('*', requireFeature(FeatureKey.CHAT_ENABLED));

chatRoutes.get('/realtime', ChatController.realtime);
chatRoutes.get('/search', ChatController.search);
chatRoutes.post('/uploads/reservations', ChatUploadController.reserve);
chatRoutes.put('/uploads/:reservationId/content', ChatUploadController.uploadContent);
chatRoutes.post('/uploads/:reservationId/complete', ChatUploadController.complete);
chatRoutes.get('/uploads/:reservationId/status', ChatUploadController.status);
chatRoutes.get('/attachments/:attachmentId/url', ChatUploadController.url);
chatRoutes.get('/attachments/:attachmentId/download', ChatUploadController.download);
chatRoutes.get('/conversations/unread-count', ChatController.unreadCount);
chatRoutes.get('/conversations', ChatController.listConversations);
chatRoutes.post('/conversations/direct', ChatController.createDirect);
chatRoutes.post('/conversations/groups', ChatController.createGroup);
chatRoutes.get('/conversations/:conversationId', ChatController.getConversation);
chatRoutes.patch('/conversations/:conversationId', ChatController.updateConversation);
chatRoutes.get('/conversations/:conversationId/messages', ChatController.listMessages);
chatRoutes.post('/conversations/:conversationId/messages', ChatController.sendMessage);
chatRoutes.post('/conversations/:conversationId/read', ChatController.markRead);
chatRoutes.put('/conversations/:conversationId/pin', ChatController.pinConversation);
chatRoutes.put('/conversations/:conversationId/mute', ChatController.muteConversation);
chatRoutes.put('/conversations/:conversationId/archive', ChatController.archiveConversation);
chatRoutes.post('/conversations/:conversationId/clear', ChatController.clearConversation);
chatRoutes.post('/conversations/:conversationId/members', ChatController.addMembers);
chatRoutes.delete('/conversations/:conversationId/members/:userId', ChatController.removeMember);
chatRoutes.patch('/conversations/:conversationId/members/:userId', ChatController.updateMemberRole);
chatRoutes.post('/conversations/:conversationId/invites', ChatController.createInvite);
chatRoutes.post('/invites/:inviteId/:decision{accept|decline}', ChatController.respondInvite);
chatRoutes.patch('/messages/:messageId', ChatController.editMessage);
chatRoutes.delete('/messages/:messageId', ChatController.deleteMessage);
chatRoutes.post('/messages/:messageId/forward', ChatController.forwardMessage);
chatRoutes.put('/messages/:messageId/star', ChatController.setStar);
chatRoutes.delete('/messages/:messageId/star', ChatController.setStar);
chatRoutes.put('/messages/:messageId/pin', ChatController.setMessagePin);
chatRoutes.delete('/messages/:messageId/pin', ChatController.setMessagePin);
chatRoutes.put('/messages/:messageId/reactions', ChatController.setReaction);
chatRoutes.delete('/messages/:messageId/reactions', ChatController.setReaction);
chatRoutes.post('/conversations/:conversationId/polls', ChatController.createPoll);
chatRoutes.post('/polls/:pollId/votes', ChatController.votePoll);
chatRoutes.post('/polls/:pollId/close', ChatController.closePoll);
chatRoutes.post('/conversations/:conversationId/events', ChatController.createEvent);
chatRoutes.put('/events/:eventId/response', ChatController.respondEvent);
