'use client';
import { useState } from 'react';
import Link from 'next/link';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { PlanName } from '@repo/types';
import { applySubscriptionCoupon, createSubscriptionCoupon, decideSubscriptionPrice, getRevenueOverview, getSubscription, quoteSubscriptionPlan, reconcileSubscription, recordBillingEvent, requestSubscriptionPrice } from '@/services/subscription-operations.service';
import { useAdminAuthStore } from '@/store/admin-auth.store';
import { canAdmin } from '@/lib/admin/permissions';

const field = 'rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-slate-200';
const button = 'rounded-lg border border-slate-700 bg-slate-800 px-3 py-2 text-sm text-slate-200 disabled:opacity-40';
const iso = (date: string) => new Date(`${date}T12:00:00.000Z`).toISOString();
export function SubscriptionOperationsPage({ tenantId }: { tenantId: string }) {
  const admin = useAdminAuthStore(state => state.admin); const client = useQueryClient();
  const query = useQuery({ queryKey: ['admin', 'subscription', tenantId], queryFn: () => getSubscription(tenantId) });
  const revenue = useQuery({ queryKey: ['admin', 'revenue'], queryFn: getRevenueOverview });
  const refresh = async () => { await Promise.all([client.invalidateQueries({ queryKey: ['admin', 'subscription', tenantId] }), client.invalidateQueries({ queryKey: ['admin', 'revenue'] })]); };
  const [plan, setPlan] = useState<PlanName>('PROFESSIONAL'); const [effectiveAt, setEffectiveAt] = useState(new Date().toISOString().slice(0, 10));
  const [coupon, setCoupon] = useState(''); const [monthly, setMonthly] = useState(''); const [unit, setUnit] = useState(''); const [expires, setExpires] = useState(''); const [reason, setReason] = useState('');
  const [newCoupon, setNewCoupon] = useState(''); const [couponPercent, setCouponPercent] = useState(''); const [couponExpiry, setCouponExpiry] = useState('');
  const [billingProvider, setBillingProvider] = useState<'MANUAL' | 'STRIPE' | 'IYZICO'>('MANUAL'); const [eventType, setEventType] = useState<'INVOICE_OPEN' | 'INVOICE_PAID' | 'INVOICE_FAILED'>('INVOICE_OPEN'); const [invoiceId, setInvoiceId] = useState(''); const [amount, setAmount] = useState('');
  const quote = useMutation({ mutationFn: () => quoteSubscriptionPlan(tenantId, plan, iso(effectiveAt)) });
  const reconcile = useMutation({ mutationFn: () => reconcileSubscription(tenantId), onSuccess: refresh });
  const applyCoupon = useMutation({ mutationFn: () => applySubscriptionCoupon(tenantId, coupon), onSuccess: refresh });
  const createCoupon = useMutation({ mutationFn: () => createSubscriptionCoupon({ code: newCoupon, percent: Number(couponPercent), expiresAt: iso(couponExpiry) }) });
  const price = useMutation({ mutationFn: () => requestSubscriptionPrice(tenantId, { monthlyAmount: Number(monthly), unitPrice: unit ? Number(unit) : null, expiresAt: iso(expires), reason }), onSuccess: refresh });
  const decision = useMutation({ mutationFn: ({ id, value }: { id: string; value: 'approve' | 'reject' }) => decideSubscriptionPrice(tenantId, id, value), onSuccess: refresh });
  const event = useMutation({ mutationFn: () => recordBillingEvent({ provider: billingProvider, providerEventId: crypto.randomUUID(), tenantId, type: eventType, providerInvoiceId: invoiceId, amount: Number(amount), currency: 'TRY', dueAt: new Date().toISOString(), ...(eventType === 'INVOICE_FAILED' ? { failureReason: 'Tahsilat başarısız' } : {}) }), onSuccess: refresh });
  const data = query.data;
  return <div className="space-y-5 text-sm text-slate-300">
    <Link href={`/admin/tenants/${tenantId}`} className="text-blue-400">← Tenant detayına dön</Link>
    <h1 className="text-xl font-semibold text-white">Abonelik ve gelir operasyonları</h1>
    {revenue.data && <section className="grid gap-3 md:grid-cols-5">{[['MRR', revenue.data.mrr], ['ARR', revenue.data.arr], ['Aktif', revenue.data.activeSubscriptions], ['Gecikmiş', revenue.data.pastDueSubscriptions], ['Başarısız fatura', revenue.data.failedInvoices]].map(([label, value]) => <div key={label} className="rounded-xl border border-slate-800 bg-slate-900 p-4"><p className="text-slate-500">{label}</p><strong className="text-lg text-white">{value}</strong></div>)}</section>}
    {query.isError && <p role="alert" className="text-red-400">Abonelik bilgileri alınamadı.</p>}
    {data && <>
      <section className="rounded-xl border border-slate-800 bg-slate-900 p-4"><h2 className="font-semibold text-white">Abonelik</h2><p>{data.snapshot.plan} · {data.snapshot.state} · {data.snapshot.provider}</p><p>MRR {data.snapshot.mrr} {data.snapshot.currency} · ARR {data.snapshot.arr} {data.snapshot.currency}</p><p>Dunning denemesi: {data.snapshot.dunningAttempt} · Sonraki deneme: {data.snapshot.nextRetryAt ?? '—'}</p><p>İndirim: {data.snapshot.discount ? `${data.snapshot.discount.code} (%${data.snapshot.discount.percent})` : 'Yok'} · Özel fiyat bitişi: {data.snapshot.customPricingExpiresAt ?? '—'}</p></section>
      <section className="space-y-3 rounded-xl border border-slate-800 bg-slate-900 p-4"><h2 className="font-semibold text-white">Plan değişikliği ön hesabı</h2><div className="flex flex-wrap gap-2"><select className={field} value={plan} onChange={e => setPlan(e.target.value as PlanName)}><option>STARTER</option><option>PROFESSIONAL</option><option>ENTERPRISE</option></select><input className={field} type="date" value={effectiveAt} onChange={e => setEffectiveAt(e.target.value)} /><button className={button} onClick={() => quote.mutate()}>Hesapla</button></div>{quote.data && <p>{quote.data.currentMonthly} → {quote.data.nextMonthly} {quote.data.currency}; kıstelyevm farkı {quote.data.proratedAmount}. Eklenen: {quote.data.moduleChanges.added.join(', ') || '—'}, kapanan: {quote.data.moduleChanges.removed.join(', ') || '—'}</p>}</section>
      <section className="space-y-3 rounded-xl border border-slate-800 bg-slate-900 p-4"><h2 className="font-semibold text-white">Entitlement mutabakatı</h2><p>Eksik: {data.snapshot.missingModules.join(', ') || 'Yok'} · Fazla: {data.snapshot.extraModules.join(', ') || 'Yok'}</p>{canAdmin(admin, 'tenant.settings.update') && <button className={button} disabled={reconcile.isPending || (!data.snapshot.missingModules.length && !data.snapshot.extraModules.length)} onClick={() => reconcile.mutate()}>Planla eşitle</button>}</section>
      {canAdmin(admin, 'tenant.plan.update') && <section className="space-y-3 rounded-xl border border-slate-800 bg-slate-900 p-4"><h2 className="font-semibold text-white">Kupon ve özel fiyat</h2><div className="flex flex-wrap gap-2"><input className={field} value={newCoupon} onChange={e => setNewCoupon(e.target.value)} placeholder="Yeni kupon"/><input className={field} type="number" min="1" max="100" value={couponPercent} onChange={e => setCouponPercent(e.target.value)} placeholder="İndirim %"/><input className={field} type="date" value={couponExpiry} onChange={e => setCouponExpiry(e.target.value)}/><button className={button} disabled={!newCoupon || !couponPercent || !couponExpiry} onClick={() => createCoupon.mutate()}>Kupon oluştur</button></div><div className="flex gap-2"><input className={field} value={coupon} onChange={e => setCoupon(e.target.value)} placeholder="Kupon kodu"/><button className={button} disabled={!coupon} onClick={() => applyCoupon.mutate()}>Kupon uygula</button></div><div className="grid gap-2 md:grid-cols-4"><input className={field} type="number" value={monthly} onChange={e => setMonthly(e.target.value)} placeholder="Aylık tutar"/><input className={field} type="number" value={unit} onChange={e => setUnit(e.target.value)} placeholder="Kullanıcı fiyatı"/><input className={field} type="date" value={expires} onChange={e => setExpires(e.target.value)}/><input className={field} value={reason} onChange={e => setReason(e.target.value)} placeholder="Gerekçe"/></div><button className={button} disabled={!monthly || !expires || reason.trim().length < 10} onClick={() => price.mutate()}>İkinci admin onayına gönder</button></section>}
      <section className="space-y-2 rounded-xl border border-slate-800 bg-slate-900 p-4"><h2 className="font-semibold text-white">Özel fiyat talepleri</h2>{data.customPrices.map(item => <div key={item.id} className="rounded-lg border border-slate-800 p-3"><p>{item.monthlyAmount} TRY · {item.state} · {item.expiresAt}</p><p>{item.reason}</p>{item.state === 'PENDING' && canAdmin(admin, 'tenant.plan.approve') && <div className="flex gap-2"><button className={button} disabled={item.requestedById === admin?.id} onClick={() => decision.mutate({ id: item.id, value: 'approve' })}>Onayla</button><button className={button} disabled={item.requestedById === admin?.id} onClick={() => decision.mutate({ id: item.id, value: 'reject' })}>Reddet</button></div>}</div>)}</section>
      {canAdmin(admin, 'tenant.plan.update') && <section className="space-y-3 rounded-xl border border-slate-800 bg-slate-900 p-4"><h2 className="font-semibold text-white">Sağlayıcı / fatura olayı</h2><div className="flex flex-wrap gap-2"><select className={field} value={billingProvider} onChange={e => setBillingProvider(e.target.value as typeof billingProvider)}><option>MANUAL</option><option>STRIPE</option><option>IYZICO</option></select><select className={field} value={eventType} onChange={e => setEventType(e.target.value as typeof eventType)}><option>INVOICE_OPEN</option><option>INVOICE_PAID</option><option>INVOICE_FAILED</option></select><input className={field} value={invoiceId} onChange={e => setInvoiceId(e.target.value)} placeholder="Sağlayıcı fatura ID"/><input className={field} type="number" value={amount} onChange={e => setAmount(e.target.value)} placeholder="Tutar"/><button className={button} disabled={!invoiceId || !amount} onClick={() => event.mutate()}>Olayı işle</button></div></section>}
      <section className="rounded-xl border border-slate-800 bg-slate-900 p-4"><h2 className="mb-2 font-semibold text-white">Faturalar</h2>{data.snapshot.invoices.map(item => <p key={item.id}>{item.providerInvoiceId} · {item.amount} {item.currency} · {item.status}{item.failureReason ? ` · ${item.failureReason}` : ''}</p>)}</section>
    </>}
  </div>;
}
